(function(){
  'use strict';
  const H=globalThis.HexEngine,V=globalThis.HexV02,X=globalThis.HexV022,Y=globalThis.HexV03,B=globalThis.HexConquestBosses,AVATARS=globalThis.HexPlayerAvatars||{};
  const STORAGE='nba_hex_conquest_v03',PROGRESS_STORAGE='nba_hex_conquest_progress_v03';
  const $=s=>document.querySelector(s),tierNames=Y.QUALITY_LABELS,positionNames={PG:'控卫',SG:'分卫',SF:'小前',PF:'大前',C:'中锋'},tagNames={shooting:'投射',creator:'持球创造',offball:'无球',playmaker:'组织',size:'体型',multi:'全能',defense:'防守',leader:'领袖',rebound:'篮板',slasher:'突破',clutch:'关键球',athletic:'运动能力',rim:'护框',post:'低位',bench:'替补'};
  let state=null,toastTimer=null,renderedPhase=null;

  function blank(seed=V.createSeed()){return{version:0.302,phase:'home',seed:V.normalizeSeed(seed),selectedTeam:null,roster:[],starterIds:[],coreIds:[],hexIds:[],budget:30,trainingPoints:0,adversity:0,intelByBoss:{},runAttemptsByBoss:{},starterPack:[],currentBossId:null,boss:null,rewardOffer:[],trainingPath:null,startedAt:null}}
  function migrate(raw){const base=blank(raw?.seed),next=Object.assign(base,raw||{},{roster:Array.isArray(raw?.roster)?raw.roster:[],starterIds:Array.isArray(raw?.starterIds)?raw.starterIds:[],coreIds:Array.isArray(raw?.coreIds)?raw.coreIds:[],hexIds:Array.isArray(raw?.hexIds)?raw.hexIds:[],starterPack:Array.isArray(raw?.starterPack)?raw.starterPack:[],rewardOffer:Array.isArray(raw?.rewardOffer)?raw.rewardOffer:[],intelByBoss:{...(raw?.intelByBoss||{})},runAttemptsByBoss:{...(raw?.runAttemptsByBoss||{})}});if(Number.isFinite(raw?.intel)&&next.intelByBoss.pistons04==null)next.intelByBoss.pistons04=raw.intel;if(Number.isFinite(raw?.runAttempts)&&next.runAttemptsByBoss.pistons04==null)next.runAttemptsByBoss.pistons04=raw.runAttempts;if(raw?.boss?.id&&!next.currentBossId)next.currentBossId=raw.boss.id;return next}
  function load(){try{const raw=localStorage.getItem(STORAGE);return raw?migrate(JSON.parse(raw)):blank()}catch{return blank()}}
  function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch{}}
  function progress(){try{return B.migrateProgress(JSON.parse(localStorage.getItem(PROGRESS_STORAGE)||'{}'))}catch{return B.initialProgress()}}
  function saveProgress(data){try{localStorage.setItem(PROGRESS_STORAGE,JSON.stringify(data))}catch{}}
  function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').classList.add('on');toastTimer=setTimeout(()=>$('#toast').classList.remove('on'),1800)}
  function player(id){return state.roster.find(p=>p.id===id)||state.starterPack.find(p=>p.id===id)||state.rewardOffer.find(p=>p.id===id)||H.players.find(p=>p.id===id)}
  function team(){return V.enhancedTeam(H,state,false)}
  function currentBoss(){return B.byId(state.currentBossId||state.boss?.id)}
  function bossIntel(id=currentBoss().id){return Math.min(2,state.intelByBoss[id]||0)}
  function bossAttempts(id=currentBoss().id){return state.runAttemptsByBoss[id]||0}
  function teamMetric(t,key){if(Number.isFinite(t[key]))return t[key];const starters=t.starters||[],avg=fn=>starters.length?starters.reduce((sum,p)=>sum+fn(p),0)/starters.length:0;if(key==='perimeterDefense')return avg(p=>p.attributes.perimeterDefense);if(key==='athletic')return avg(p=>p.attributes.athleticism);if(key==='size')return avg(p=>p.hidden.size)*20;if(key==='post')return avg(p=>p.positions.some(x=>x==='PF'||x==='C')?(p.attributes.fin+p.attributes.mid+p.hidden.size*10)/2.1:55);if(key==='creator')return t.playmaking;return 0}
  function choiceFits(choice,t=team()){if(choice.stats)return choice.stats.every((key,i)=>teamMetric(t,key)>=(choice.thresholds?.[i]||80));return teamMetric(t,choice.stat)>=(choice.threshold||80)}
  function choiceBonus(choice,t=team()){return (choice.bonus||0)*(choiceFits(choice,t)?1:.42)}
  function teamMark(t,size=''){const code=t.abbreviation||t.id;return`<span class="team-mark ${size}" style="--team-a:${t.colors?.[0]||'#39d9ff'};--team-b:${t.colors?.[1]||'#f5f7fb'}"><span>${code}</span><img src="./assets/team-logos/${code}.svg" alt="" loading="lazy" decoding="async" onerror="this.remove()"></span>`}
  function avatar(p,size=''){const src=AVATARS[p.id],short=p.name.replace(/[·-]/g,'').slice(-2);return`<span class="player-avatar ${size}" aria-hidden="true"><span>${short}</span>${src?`<img src="${src}" alt="" loading="lazy" decoding="async" onerror="this.remove()">`:''}</span>`}
  function identity(p){return`<span class="player-identity">${avatar(p)}<span><b>${p.name}</b><small>${p.season} · ${p.age}岁</small></span></span>`}
  function card(p,{action='',index=0}={}){const tag=p.tags.slice(0,3).map(x=>tagNames[x]||x).join(' · '),open=action?'button':'article',close=open==='button'?'button':'article',attr=action?`data-${action}="${p.id}"`:'';return`<${open} class="v03-player-card q-${p.cardQuality||p.tier}" ${attr} style="--deal:${index*.08}s"><span class="card-quality">${tierNames[p.cardQuality||p.tier]||p.tier}</span><span class="card-year">${p.season}</span>${identity(p)}<p>${p.positions.map(x=>positionNames[x]||x).join(' / ')} · ${tag}</p><div class="card-rating"><span>能力<strong>${p.currentRating||Math.round(H.playerOff(p))}</strong></span><span>潜力<strong>${p.potential||'—'}</strong></span><span>费用<strong>${p.cost||'—'}</strong></span></div><div class="card-stars">${Y.stars(p)}</div></${close}>`}
  function seedStrip(){return`<div class="seed-strip"><span class="mode-chip">历史征服</span><span>本局Seed <b>${state.seed}</b></span></div>`}
  function hud(){const p=progress();return`<div class="conquest-hud"><span>已征服 <b>${B.clearedCount(p)}/${B.TOTAL_BOSSES}</b></span><span>星星 <b>${B.totalStars(p)}/${B.TOTAL_BOSSES*3}</b></span><span>预算 <b>${Y.budgetUsed(state.roster)}/${state.budget}</b></span><span>训练点 <b>${state.trainingPoints}</b></span><span>逆境点 <b>${state.adversity}/3</b></span></div>`}

  function startNew(){state=blank();state.phase='team_select';state.startedAt=Date.now();save();render()}
  function chooseTeam(id){const club=X.teamById(id);if(!club)return;state.selectedTeam=id;state.starterPack=Y.initialPack(H,V,state.seed);state.phase='starter_pack';save();render()}
  function acceptPack(){state.roster=state.starterPack.map(p=>({...p,positions:[...p.positions],attributes:{...p.attributes},hidden:{...p.hidden},tags:[...p.tags]}));state.starterIds=state.roster.map(p=>p.id);state.coreIds=[...state.roster].sort((a,b)=>H.playerOff(b)-H.playerOff(a)).slice(0,3).map(p=>p.id);state.phase='hub';save();render()}
  function openBoss(id){const p=progress();if(!B.isUnlocked(id,p))return toast('先击败上一支历史冠军队');state.currentBossId=id;state.boss=null;state.phase='boss_brief';save();render()}
  function beginBoss(strategyId){const boss=currentBoss(),choice=boss.strategies.find(x=>x.id===strategyId);if(!choice)return;const t=team(),attempt=bossAttempts(boss.id)+1,rng=V.rngFor(state.seed,`conquest_${boss.id}_half`,attempt),edge=t.power-boss.power,fit=choiceFits(choice,t),own=Math.round(49+edge*.43+(fit?2.5:0)+(rng()-.5)*9),opp=Math.round(51+(boss.number-1)*.6+(rng()-.5)*8);state.boss={id:boss.id,strategy:strategyId,strategyFit:fit,mid:null,midFit:false,clutch:null,clutchFit:false,attempt,own,opp,won:null,growthPlayerId:null,stars:0};state.phase='boss_mid';save();render()}
  function chooseMid(id){const boss=currentBoss(),choice=boss.midChoices.find(x=>x.id===id);if(!choice)return;const t=team(),rng=V.rngFor(state.seed,`conquest_${boss.id}_third`,state.boss.attempt),fit=choiceFits(choice,t);state.boss.mid=id;state.boss.midFit=fit;state.boss.own+=Math.round(24+(fit?choice.ownGood:choice.ownBase)+(rng()-.5)*6);state.boss.opp+=Math.round(24+(choice.opp||0)+(rng()-.5)*6);state.phase='boss_clutch';save();render()}
  function growRolePlayer(){const rank={S:5,A:4,B:3,C:2,D:1},candidates=state.roster.filter(p=>['ROLE','STARTER'].includes(p.cardQuality||p.tier)).sort((a,b)=>(rank[b.potential]||0)-(rank[a.potential]||0));const p=candidates[0];if(!p)return null;p.growth=(p.growth||0)+1;p.attributes.perimeterDefense=Math.min(99,p.attributes.perimeterDefense+2);p.currentRating=Math.min(99,(p.currentRating||70)+1);if(p.growth>=2&&p.stars<3){p.stars++;p.growth=0;p.cost=Math.min(7,p.cost+1)}return p.id}
  function thirdStarEarned(boss){const rule=boss.star3;if(rule.type==='noLegend')return state.roster.every(x=>(x.cardQuality||x.tier)!=='LEGEND');if(rule.type==='strategy')return state.boss.strategy===rule.id;if(rule.type==='combo')return state.boss.strategy===rule.strategy&&state.boss.mid===rule.mid;return false}
  function chooseClutch(id){const boss=currentBoss(),choice=boss.clutchChoices.find(x=>x.id===id);if(!choice)return;const t=team(),rng=V.rngFor(state.seed,`conquest_${boss.id}_finish`,state.boss.attempt),strategy=boss.strategies.find(x=>x.id===state.boss.strategy),mid=boss.midChoices.find(x=>x.id===state.boss.mid),intel=bossIntel(boss.id)*.017,scoreEdge=(state.boss.own-state.boss.opp)*.014,chance=H.clamp(.49+(t.power-boss.power)*.026+choiceBonus(strategy,t)+choiceBonus(mid,t)+choiceBonus(choice,t)+intel+scoreEdge,.12,.90),won=rng()<chance;state.boss.clutch=id;state.boss.clutchFit=choiceFits(choice,t);state.runAttemptsByBoss[boss.id]=bossAttempts(boss.id)+1;let own=state.boss.own+Math.round(23+(t.offense-82)*.16+(choice.ownFinal||0)+(rng()-.5)*7),opp=state.boss.opp+Math.round(23-(t.defense-82)*.13+(choice.oppFinal||0)+(boss.number-1)*.45+(rng()-.5)*7);if(won&&own<=opp)own=opp+Math.ceil(2+rng()*5);if(!won&&own>=opp)opp=own+Math.ceil(2+rng()*5);Object.assign(state.boss,{own,opp,won});const p=progress(),record=p.bosses[boss.id];record.attempts++;if(won){state.boss.stars=1+(opp<=boss.star2Max?1:0)+(thirdStarEarned(boss)?1:0);record.cleared=true;record.stars=Math.max(record.stars,state.boss.stars);record.bestScore=!record.bestScore||own-opp>record.bestScore.own-record.bestScore.opp?{own,opp}:record.bestScore;if(rng()<.65)state.boss.growthPlayerId=growRolePlayer()}else{state.intelByBoss[boss.id]=Math.min(2,bossIntel(boss.id)+1);state.adversity=Math.min(3,state.adversity+1);if(state.runAttemptsByBoss[boss.id]<=2)state.trainingPoints++}saveProgress(p);state.phase='boss_result';save();render()}
  function openReward(){state.phase='reward';save();render()}
  function rewardPack(){const boss=currentBoss(),profiles=Y.createProfiles(H,V),chosen=new Set(state.roster.map(p=>p.id)),pool=H.players.filter(p=>!chosen.has(p.id)&&p.tags.some(tag=>boss.rewardTags.includes(tag))),rng=V.rngFor(state.seed,`${boss.id}_reward_pack`,progress().bosses[boss.id].attempts);state.rewardOffer=H.sample(pool,Math.min(3,pool.length),rng).map(p=>Y.cardFrom(H,V,p,profiles));state.phase='reward_player';save();render()}
  function chooseReward(type){if(type==='training'){state.trainingPoints+=2;state.phase='hub'}else if(type==='budget'){state.budget+=2;state.phase='hub'}else return rewardPack();save();render()}
  function chooseRewardPlayer(id){const p=state.rewardOffer.find(x=>x.id===id);if(!p)return;if(!Y.canAdd(state.roster,p,state.budget))return toast(state.roster.length>=8?'阵容已经满8人':'王朝预算不足，可选择其他奖励');state.roster.push(p);state.phase='hub';state.rewardOffer=[];save();render()}
  function openTraining(){if(state.trainingPoints<2)return toast('至少需要2训练点');state.phase='training';save();render()}
  function chooseTrainingPath(id){if(!Y.TRAINING_PATHS[id])return;state.trainingPath=id;state.phase='training_target';save();render()}
  function chooseTrainingTarget(id){const index=state.roster.findIndex(p=>p.id===id);if(index<0||state.trainingPoints<2)return;state.roster[index]=Y.trainPlayer(state.roster[index],state.trainingPath);state.trainingPoints-=2;state.trainingPath=null;state.phase='hub';save();render();toast(`${state.roster[index].name}完成训练`)}

  function fitLabel(choice,t){const good=choiceFits(choice,t);return`<em class="fit ${good?'good':''}">阵容适配：${good?'高':'一般'}</em>`}
  function renderChoice(choice,type,t){return`<button class="choice-btn" data-${type}="${choice.id}"><strong>${choice.title}</strong><span>${choice.description}</span>${fitLabel(choice,t)}</button>`}
  function renderHome(){const hasRun=state.selectedTeam&&state.roster.length;return`<section class="panel"><div class="hero"><div class="eyebrow">V0.3 · 历史征服</div><h1>穿越NBA历史<br>击败冠军王朝</h1><p>开启5张混合品质球员卡，在单局内培养阵容，并用真实篮球策略挑战各时代传奇球队。</p><div class="conquest-intro"><span><b>5张</b>初始球员卡</span><span><b>30点</b>王朝预算</span><span><b>3支</b>当前可玩Boss</span></div><div class="hero-actions"><button class="primary" data-new>开始历史征服</button>${hasRun?'<button class="ghost" data-continue>继续本轮征服</button>':''}<a class="ghost" href="./hex.html">返回海克斯王朝</a></div></div><p class="save-note">历史征服使用独立本地存档，不会覆盖王朝赛季或总经理模式。</p></section>`}
  function renderTeamSelect(){const groups=[['EAST','东部联盟'],['WEST','西部联盟']];return`<section class="panel">${seedStrip()}<div class="section-head"><div><div class="eyebrow">选择球队身份</div><h2>以哪支球队开启征服</h2></div><span>只影响球队身份与报告</span></div>${groups.map(([conf,label])=>`<div class="team-group"><h3>${label}</h3><div class="team-select-grid">${X.teams.filter(t=>t.conference===conf).map(t=>`<button class="team-choice" data-team="${t.id}" style="--team-a:${t.colors[0]};--team-b:${t.colors[1]}">${teamMark(t)}<span><b>${t.chineseName}</b><small>${t.historicalTags.slice(0,2).join(' · ')}</small></span></button>`).join('')}</div></div>`).join('')}</section>`}
  function renderStarterPack(){return`<section class="panel">${seedStrip()}<div class="section-head"><div><div class="eyebrow">初始球员包 · 5张全部加入</div><h2>你的征服阵容</h2></div><span>至少1张优质首发或更高</span></div><p class="pack-note">品质决定基础层级，不代表最终上限。普通球员可以在这一局中升星和成长。</p><div class="starter-pack">${state.starterPack.map((p,i)=>card(p,{index:i})).join('')}</div><div class="budget-preview"><span>初始预算占用</span><b>${Y.budgetUsed(state.starterPack)} / ${state.budget}</b></div><div class="footer-actions"><button class="primary" data-accept>收下5张球员卡</button></div></section>`}
  function bossCard(boss,p){const record=p.bosses[boss.id],unlocked=B.isUnlocked(boss.id,p),status=record.cleared?'completed':unlocked?'unlocked':'locked',tag=record.cleared?'已征服':unlocked?'可以挑战':'尚未解锁',body=`<span>副本 ${boss.number} · 危险度 ${'★'.repeat(boss.danger)}</span><h3>${boss.shortName}</h3><p>${boss.mechanicDescription}</p><strong>Boss：${boss.bossName}</strong><small>${tag} · ${'★'.repeat(record.stars)}${'☆'.repeat(3-record.stars)} · ${record.attempts}次</small>`;return unlocked?`<button class="boss-card ${status}" data-boss="${boss.id}">${body}</button>`:`<article class="boss-card ${status}">${body}</article>`}
  function renderHub(){const club=X.teamById(state.selectedTeam),p=progress(),t=team(),chapters=[...new Set(B.BOSSES.map(b=>b.chapter))];return`<section class="panel">${seedStrip()}<div class="club-banner">${teamMark(club,'small')}<span><b>${club.chineseName}</b><small>阵容成熟度 ${t.power>=90?'★★★★':t.power>=86?'★★★':'★★'} · ${t.builds?.[0]?.name||'Build尚未成型'}</small></span></div>${hud()}${chapters.map(chapter=>`<div class="chapter"><div class="chapter-head"><div class="eyebrow">${chapter}</div><h2>历史副本地图</h2></div><div class="boss-grid">${B.BOSSES.filter(b=>b.chapter===chapter).map(b=>bossCard(b,p)).join('')}</div></div>`).join('')}<div class="roadmap-card"><span>后续章节</span><b>热火 · 凯尔特人 · 公牛 · 湖人 · 勇士</b><small>本轮先完成火箭与马刺，剩余5个Boss尚未开放。</small></div><div class="roster-ribbon">${state.roster.map(p=>`<span class="q-${p.cardQuality||p.tier}"><b>${p.name}</b><small>${Y.stars(p)} · ${p.cost}费</small></span>`).join('')}</div><div class="map-actions"><button class="ghost" data-training ${state.trainingPoints<2?'disabled':''}>球员训练（2点）</button><button class="ghost" data-roster-info>阵容能力 ${Math.round(t.power)}</button></div></section>`}
  function renderBossBrief(){const boss=currentBoss(),t=team(),intel=bossIntel();return`<section class="panel">${seedStrip()}${hud()}<div class="boss-hero"><div class="eyebrow">HISTORICAL BOSS ${String(boss.number).padStart(2,'0')}</div><h1>${boss.chineseName}</h1><p>${boss.subtitle}</p></div><div class="boss-mechanic"><span>BOSS机制 · ${boss.theme}</span><h2>${boss.mechanicTitle}</h2><p>${boss.mechanicDescription}</p></div><div class="boss-roster">${boss.roster.map(([name,pos])=>`<article class="boss-player"><b>${name}</b><span>${pos}</span></article>`).join('')}</div><div class="star-goals"><span>三星目标</span><b>① 击败Boss　② 对手不超过${boss.star2Max}分　③ ${boss.star3.description}</b></div><div class="section-head"><div><div class="eyebrow">赛前策略</div><h2>制定针对方案</h2></div><span>你的阵容能力 ${Math.round(t.power)}</span></div><div class="strategy-grid">${boss.strategies.map(x=>renderChoice(x,'strategy',t)).join('')}</div>${intel?`<div class="intel"><b>已解锁Boss情报：</b>${boss.intel[intel-1]}</div>`:''}</section>`}
  function renderBossMid(){const boss=currentBoss(),t=team();return`<section class="panel">${seedStrip()}<div class="scoreboard"><div><span>你的球队</span><b>${state.boss.own}</b></div><em>半场</em><div><span>${boss.shortName}</span><b>${state.boss.opp}</b></div></div><p class="boss-alert">${boss.midAlert}</p><div class="section-head"><div><div class="eyebrow">比赛中事件</div><h2>${boss.midTitle}</h2></div><span>选择会影响末节局势</span></div><div class="decision-grid">${boss.midChoices.map(x=>renderChoice(x,'mid',t)).join('')}</div></section>`}
  function renderBossClutch(){const boss=currentBoss(),t=team(),behind=state.boss.own<state.boss.opp;return`<section class="panel">${seedStrip()}<div class="scoreboard"><div><span>你的球队</span><b>${state.boss.own}</b></div><em>第三节结束</em><div><span>${boss.shortName}</span><b>${state.boss.opp}</b></div></div><p class="boss-alert">${behind?boss.clutchBehind:boss.clutchLead}</p><div class="section-head"><div><div class="eyebrow">第四节决策</div><h2>最后12分钟</h2></div><span>决定胜负</span></div><div class="decision-grid">${boss.clutchChoices.map(x=>renderChoice(x,'clutch',t)).join('')}</div></section>`}
  function renderBossResult(){const boss=currentBoss(),b=state.boss,growth=b.growthPlayerId&&player(b.growthPlayerId),rewardLabel=boss.number===B.BOSSES.length?'领取战利品并查看地图':'选择战利品';return`<section class="panel">${seedStrip()}<div class="result-hero ${b.won?'':'loss'}"><span>${b.won?'BOSS CLEARED':'CHALLENGE FAILED'}</span><h1>${b.own}-${b.opp}</h1><b>${b.won?boss.winText:boss.lossText}</b></div>${growth?`<article class="story-card"><span>成长事件 · 证明自己</span><b>${growth.season} ${growth.name}</b><p>在Boss战中完成关键对位，防守与成长进度获得提升。</p></article>`:''}${b.won?`<div class="boss-mechanic"><span>本次评价</span><h2>${'★'.repeat(b.stars)}${'☆'.repeat(3-b.stars)}</h2><p>击败Boss${b.opp<=boss.star2Max?` · 对手不超过${boss.star2Max}分`:''}${thirdStarEarned(boss)?` · ${boss.star3.description}`:''}</p></div><div class="footer-actions"><button class="primary" data-loot>${rewardLabel}</button></div>`:`<div class="intel"><b>失败收益：</b>Boss情报已更新${state.runAttemptsByBoss[boss.id]<=2?'，获得1训练点':''}，逆境点增加。你可以立即重试，也可以返回地图训练球员。</div><div class="footer-actions"><button class="primary" data-retry>重新挑战</button><button class="ghost" data-hub>返回征服地图</button></div>`}</section>`}
  function renderReward(){const boss=currentBoss();return`<section class="panel">${seedStrip()}<div class="section-head"><div><div class="eyebrow">${boss.shortName}战利品 · 三选一</div><h2>这次胜利怎样改变Build</h2></div><span>只能选择一项</span></div><div class="reward-grid"><button class="reward-card" data-reward="training"><span>稳定成长</span><h3>训练点 +2</h3><p>培养现有球员，推进升星与属性成长。</p></button><button class="reward-card" data-reward="player"><span>${boss.theme}掉落</span><h3>${boss.rewardName}</h3><p>${boss.rewardDescription}</p></button><button class="reward-card" data-reward="budget"><span>阵容空间</span><h3>王朝预算 +2</h3><p>为后续高费用球员和升星培养留下空间。</p></button></div></section>`}
  function renderRewardPlayer(){const boss=currentBoss();return`<section class="panel">${seedStrip()}${hud()}<div class="section-head"><div><div class="eyebrow">${boss.rewardName}</div><h2>选择一张球员卡</h2></div><span>受8人上限与预算限制</span></div><div class="content v03-offer">${state.rewardOffer.map((p,i)=>card(p,{action:'reward-player',index:i})).join('')}</div></section>`}
  function renderTraining(){return`<section class="panel">${seedStrip()}${hud()}<div class="section-head"><div><div class="eyebrow">球员训练 · 消耗2点</div><h2>选择训练方向</h2></div><span>高潜力球员收益更高</span></div><div class="training-grid">${Object.entries(Y.TRAINING_PATHS).map(([id,x])=>`<button class="training-card" data-training-path="${id}"><strong>${x.name}</strong><span>${x.description}</span></button>`).join('')}</div></section>`}
  function renderTrainingTarget(){const x=Y.TRAINING_PATHS[state.trainingPath];return`<section class="panel">${seedStrip()}${hud()}<div class="section-head"><div><div class="eyebrow">${x.name}</div><h2>选择培养球员</h2></div><span>训练后返回征服地图</span></div><div class="content v03-offer">${state.roster.map((p,i)=>card(p,{action:'training-target',index:i})).join('')}</div></section>`}

  function goHub(){state.phase='hub';save();render()}
  function contextBack(){if(['boss_brief','boss_mid','boss_clutch','boss_result','reward','reward_player','training'].includes(state.phase))state.phase='hub';else if(state.phase==='training_target')state.phase='training';else state.phase='home';save();render()}
  function updateTop(){const back=$('[data-context-back]'),secondary=state.phase!=='home';back?.classList.toggle('hidden',!secondary);if(back)back.onclick=contextBack}
  function render(){const views={home:renderHome,team_select:renderTeamSelect,starter_pack:renderStarterPack,hub:renderHub,boss_brief:renderBossBrief,boss_mid:renderBossMid,boss_clutch:renderBossClutch,boss_result:renderBossResult,reward:renderReward,reward_player:renderRewardPlayer,training:renderTraining,training_target:renderTrainingTarget},phaseChanged=renderedPhase!==state.phase;$('#screen').innerHTML=(views[state.phase]||renderHome)();updateTop();bind();if(phaseChanged){renderedPhase=state.phase;window.scrollTo({top:0,left:0,behavior:'instant'})}}
  function bind(){document.querySelectorAll('[data-new]').forEach(b=>b.addEventListener('click',startNew));$('[data-continue]')?.addEventListener('click',()=>{state.phase=state.phase==='home'?'hub':state.phase;render()});document.querySelectorAll('[data-team]').forEach(b=>b.addEventListener('click',()=>chooseTeam(b.dataset.team)));$('[data-accept]')?.addEventListener('click',acceptPack);document.querySelectorAll('[data-boss]').forEach(b=>b.addEventListener('click',()=>openBoss(b.dataset.boss)));document.querySelectorAll('[data-strategy]').forEach(b=>b.addEventListener('click',()=>beginBoss(b.dataset.strategy)));document.querySelectorAll('[data-mid]').forEach(b=>b.addEventListener('click',()=>chooseMid(b.dataset.mid)));document.querySelectorAll('[data-clutch]').forEach(b=>b.addEventListener('click',()=>chooseClutch(b.dataset.clutch)));$('[data-loot]')?.addEventListener('click',openReward);document.querySelectorAll('[data-reward]').forEach(b=>b.addEventListener('click',()=>chooseReward(b.dataset.reward)));document.querySelectorAll('[data-reward-player]').forEach(b=>b.addEventListener('click',()=>chooseRewardPlayer(b.dataset.rewardPlayer)));$('[data-retry]')?.addEventListener('click',()=>openBoss(currentBoss().id));$('[data-hub]')?.addEventListener('click',goHub);$('[data-training]')?.addEventListener('click',openTraining);document.querySelectorAll('[data-training-path]').forEach(b=>b.addEventListener('click',()=>chooseTrainingPath(b.dataset.trainingPath)));document.querySelectorAll('[data-training-target]').forEach(b=>b.addEventListener('click',()=>chooseTrainingTarget(b.dataset.trainingTarget)));$('[data-roster-info]')?.addEventListener('click',()=>toast(`当前阵容能力 ${Math.round(team().power)}，预算 ${Y.budgetUsed(state.roster)}/${state.budget}`))}

  state=load();if(!['home','team_select','starter_pack','hub','boss_brief','boss_mid','boss_clutch','boss_result','reward','reward_player','training','training_target'].includes(state.phase))state.phase='home';render();
})();
