(function(){
  'use strict';
  const H=globalThis.HexEngine,V=globalThis.HexV02,X=globalThis.HexV022,Y=globalThis.HexV03,B=globalThis.HexConquestBosses,AVATARS=globalThis.HexPlayerAvatars||{};
  const STORAGE='nba_hex_conquest_v03',PROGRESS_STORAGE='nba_hex_conquest_progress_v03';
  const $=s=>document.querySelector(s),tierNames=Y.QUALITY_LABELS,positionNames={PG:'控卫',SG:'分卫',SF:'小前',PF:'大前',C:'中锋'},tagNames={shooting:'投射',creator:'持球创造',offball:'无球',playmaker:'组织',size:'体型',multi:'全能',defense:'防守',leader:'领袖',rebound:'篮板',slasher:'突破',clutch:'关键球',athletic:'运动能力',rim:'护框',post:'低位',bench:'替补'};
  let state=null,toastTimer=null,renderedPhase=null;

  function blank(seed=V.createSeed()){return{version:0.32,phase:'home',seed:V.normalizeSeed(seed),selectedTeam:null,roster:[],starterIds:[],coreIds:[],hexIds:[],budget:30,trainingPoints:0,adversity:0,intelByBoss:{},runAttemptsByBoss:{},starterPack:[],currentBossId:null,boss:null,rewardOffer:[],trainingPath:null,trainingTargetId:null,freeTraining:false,pendingDuplicateId:null,pendingHexId:null,growthFeedback:null,routeChoices:[],duplicateStats:{growth:0,training:0},rewardStats:{training:0,player:0,budget:0,upgrade:0,hex:0},playerHexIds:[],awakenings:[],startedAt:null}}
  function migrate(raw){const base=blank(raw?.seed),next=Object.assign(base,raw||{},{version:.32,roster:Array.isArray(raw?.roster)?raw.roster.map(Y.runtimePlayer):[],starterIds:Array.isArray(raw?.starterIds)?raw.starterIds:[],coreIds:Array.isArray(raw?.coreIds)?raw.coreIds:[],hexIds:Array.isArray(raw?.hexIds)?raw.hexIds:[],starterPack:Array.isArray(raw?.starterPack)?raw.starterPack.map(Y.runtimePlayer):[],rewardOffer:Array.isArray(raw?.rewardOffer)?raw.rewardOffer.map(Y.runtimePlayer):[],intelByBoss:{...(raw?.intelByBoss||{})},runAttemptsByBoss:{...(raw?.runAttemptsByBoss||{})},routeChoices:[...(raw?.routeChoices||[])],duplicateStats:{growth:0,training:0,...(raw?.duplicateStats||{})},rewardStats:{training:0,player:0,budget:0,upgrade:0,hex:0,...(raw?.rewardStats||{})},playerHexIds:[...(raw?.playerHexIds||[])],awakenings:[...(raw?.awakenings||[])]});if(Number.isFinite(raw?.intel)&&next.intelByBoss.pistons04==null)next.intelByBoss.pistons04=raw.intel;if(Number.isFinite(raw?.runAttempts)&&next.runAttemptsByBoss.pistons04==null)next.runAttemptsByBoss.pistons04=raw.runAttempts;if(raw?.boss?.id&&!next.currentBossId)next.currentBossId=raw.boss.id;return next}
  function load(){try{const raw=localStorage.getItem(STORAGE);return raw?migrate(JSON.parse(raw)):blank()}catch{return blank()}}
  function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch{}}
  function progress(){try{return B.migrateProgress(JSON.parse(localStorage.getItem(PROGRESS_STORAGE)||'{}'))}catch{return B.initialProgress()}}
  function saveProgress(data){try{localStorage.setItem(PROGRESS_STORAGE,JSON.stringify(data))}catch{}}
  function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').classList.add('on');toastTimer=setTimeout(()=>$('#toast').classList.remove('on'),1800)}
  function player(id){return state.roster.find(p=>p.id===id)||state.starterPack.find(p=>p.id===id)||state.rewardOffer.find(p=>p.id===id)||H.players.find(p=>p.id===id)}
  function team(){const t=V.enhancedTeam(H,state,false),ids=new Set(state?.awakenings||[]);let boost=ids.size*.35;if(ids.has('rodman_rebound')){t.rebound=Math.min(100,t.rebound+4);boost+=.5}if(ids.has('draymond_command')){t.defense=Math.min(100,t.defense+3);t.chemistry=Math.min(100,t.chemistry+2);boost+=.6}if(ids.has('manu_sixth')){t.offense=Math.min(100,t.offense+2);boost+=.4}if(ids.has('klay_light')||ids.has('iggy_playoffs')||ids.has('jrue_lock'))boost+=.45;t.power=Math.round(Math.min(105,t.power+boost)*10)/10;return t}
  function currentBoss(){return B.byId(state.currentBossId||state.boss?.id)}
  function bossIntel(id=currentBoss().id){return Math.min(2,state.intelByBoss[id]||0)}
  function bossAttempts(id=currentBoss().id){return state.runAttemptsByBoss[id]||0}
  function teamMetric(t,key){if(Number.isFinite(t[key]))return t[key];const starters=t.starters||[],avg=fn=>starters.length?starters.reduce((sum,p)=>sum+fn(p),0)/starters.length:0;if(key==='perimeterDefense')return avg(p=>p.attributes.perimeterDefense);if(key==='athletic')return avg(p=>p.attributes.athleticism);if(key==='size')return avg(p=>p.hidden.size)*20;if(key==='post')return avg(p=>p.positions.some(x=>x==='PF'||x==='C')?(p.attributes.fin+p.attributes.mid+p.hidden.size*10)/2.1:55);if(key==='creator')return t.playmaking;return 0}
  function choiceFits(choice,t=team()){if(choice.stats)return choice.stats.every((key,i)=>teamMetric(t,key)>=(choice.thresholds?.[i]||80));return teamMetric(t,choice.stat)>=(choice.threshold||80)}
  function choiceBonus(choice,t=team()){return (choice.bonus||0)*(choiceFits(choice,t)?1:.42)}
  function buildTags(){const t=team();return[...(t.builds||[]).filter(x=>x.level>0).map(x=>String(x.tag||'').toLowerCase()),...state.playerHexIds]}
  function replacePlayer(next,reason){const index=state.roster.findIndex(p=>p.id===next.id&&p.season===next.season);if(index<0)return;const before=state.roster[index],checked=Y.checkAwakening(next,{starterIds:state.starterIds,buildTags:buildTags()});state.roster[index]=checked.player;if(checked.awakened&&!state.awakenings.includes(checked.awakened.id)){state.awakenings.push(checked.awakened.id);state.growthFeedback={type:'awakening',title:'🔥 球员觉醒',name:next.name,detail:checked.awakened.name,description:checked.awakened.description}}else if(checked.player.stars>before.stars){const last=checked.player.upgradeHistory.filter(x=>x.type==='STAR_UP').at(-1);state.growthFeedback={type:'star',title:'球员升星',name:next.name,detail:`${'★'.repeat(before.stars)} → ${'★'.repeat(checked.player.stars)}`,description:reason,gains:last?.gains||{}}}}
  function diagnosis(){const t=team(),left=state.budget-Y.budgetUsed(state.roster),risks=[];if(t.defense<82)risks.push('整体防守偏弱');if(t.space<80)risks.push('外线空间不足');if(t.playmaking<82)risks.push('第二组织点不足');if(t.rebound<80)risks.push('篮板保护偏弱');if(left<=3)risks.push(`预算仅剩${left}`);return risks.slice(0,3)}
  function teamMark(t,size=''){const code=t.abbreviation||t.id;return`<span class="team-mark ${size}" style="--team-a:${t.colors?.[0]||'#39d9ff'};--team-b:${t.colors?.[1]||'#f5f7fb'}"><span>${code}</span><img src="./assets/team-logos/${code}.svg" alt="" loading="lazy" decoding="async" onerror="this.remove()"></span>`}
  function avatar(p,size=''){const src=AVATARS[p.id],short=p.name.replace(/[·-]/g,'').slice(-2);return`<span class="player-avatar ${size}" aria-hidden="true"><span>${short}</span>${src?`<img src="${src}" alt="" loading="lazy" decoding="async" onerror="this.remove()">`:''}</span>`}
  function identity(p){return`<span class="player-identity">${avatar(p)}<span><b>${p.name}</b><small>${p.season} · ${p.age}岁</small></span></span>`}
  function card(p,{action='',index=0}={}){const tag=p.tags.slice(0,3).map(x=>tagNames[x]||x).join(' · '),open=action?'button':'article',close=open==='button'?'button':'article',attr=action?`data-${action}="${p.id}"`:'';return`<${open} class="v03-player-card q-${p.cardQuality||p.tier} stars-${p.stars||1}" ${attr} style="--deal:${index*.08}s"><span class="card-quality">${tierNames[p.cardQuality||p.tier]||p.tier}${p.stars===3?' · 完全体':''}</span><span class="card-year">${p.season}</span>${identity(p)}<p>${p.positions.map(x=>positionNames[x]||x).join(' / ')} · ${tag}</p><div class="card-rating"><span>能力<strong>${p.currentRating||Math.round(H.playerOff(p))}</strong></span><span>潜力<strong>${p.potential||'—'}</strong></span><span>费用<strong>${p.cost||'—'}</strong></span></div><div class="card-stars">${Y.stars(p)} <small>成长 ${p.starXp||0}/${p.stars===1?2:p.stars===2?3:'MAX'}</small>${p.awakenings?.length?'<i>🔥 已觉醒</i>':''}</div></${close}>`}
  function seedStrip(){return`<div class="seed-strip"><span class="mode-chip">历史征服</span><span>本局Seed <b>${state.seed}</b></span></div>`}
  function hud(){const p=progress();return`<div class="conquest-hud"><span>已征服 <b>${B.clearedCount(p)}/${B.TOTAL_BOSSES}</b></span><span>星星 <b>${B.totalStars(p)}/${B.TOTAL_BOSSES*3}</b></span><span>预算 <b>${Y.budgetUsed(state.roster)}/${state.budget}</b></span><span>训练点 <b>${state.trainingPoints}</b></span><span>逆境点 <b>${state.adversity}/3</b></span></div>`}

  function startNew(){state=blank();state.phase='team_select';state.startedAt=Date.now();save();render()}
  function chooseTeam(id){const club=X.teamById(id);if(!club)return;state.selectedTeam=id;state.starterPack=Y.initialPack(H,V,state.seed);state.phase='starter_pack';save();render()}
  function acceptPack(){state.roster=state.starterPack.map(p=>({...p,positions:[...p.positions],attributes:{...p.attributes},hidden:{...p.hidden},tags:[...p.tags]}));state.starterIds=state.roster.map(p=>p.id);state.coreIds=[...state.roster].sort((a,b)=>H.playerOff(b)-H.playerOff(a)).slice(0,3).map(p=>p.id);state.phase='hub';save();render()}
  function openBoss(id){const p=progress();if(!B.isUnlocked(id,p))return toast('先击败上一支历史冠军队');state.currentBossId=id;state.boss=null;state.phase='boss_brief';save();render()}
  function beginBoss(strategyId){const boss=currentBoss(),choice=boss.strategies.find(x=>x.id===strategyId);if(!choice)return;const t=team(),attempt=bossAttempts(boss.id)+1,rng=V.rngFor(state.seed,`conquest_${boss.id}_half`,attempt),edge=t.power-boss.power,fit=choiceFits(choice,t),own=Math.round(49+edge*.43+(fit?2.5:0)+(rng()-.5)*9),opp=Math.round(51+(boss.number-1)*.6+(rng()-.5)*8),mechanics=boss.id==='rockets95'?{hakeemPoints:Math.round(17+(strategyId==='single'?7:strategyId==='front'?2:4)+rng()*5),rocketThrees:Math.round(4+(strategyId==='front'?2:strategyId==='single'?0:1)+rng()*3)}:boss.id==='spurs14'?{teamStack:Math.min(5,Math.round(2+(strategyId==='switch'?0:1)+rng()*2)),beautifulTriggers:0}:{};state.boss={id:boss.id,strategy:strategyId,strategyFit:fit,mid:null,midFit:false,clutch:null,clutchFit:false,attempt,own,opp,won:null,growthPlayerId:null,stars:0,...mechanics};state.phase='boss_mid';save();render()}
  function chooseMid(id){const boss=currentBoss(),choice=boss.midChoices.find(x=>x.id===id);if(!choice)return;const t=team(),rng=V.rngFor(state.seed,`conquest_${boss.id}_third`,state.boss.attempt),fit=choiceFits(choice,t);state.boss.mid=id;state.boss.midFit=fit;state.boss.own+=Math.round(24+(fit?choice.ownGood:choice.ownBase)+(rng()-.5)*6);state.boss.opp+=Math.round(24+(choice.opp||0)+(rng()-.5)*6);if(boss.id==='rockets95'){state.boss.hakeemPoints+=id==='lateDouble'?4:id==='denyCorner'?8:6;state.boss.rocketThrees+=id==='denyCorner'?1:id==='lateDouble'?3:2}if(boss.id==='spurs14'){state.boss.teamStack=Math.max(0,Math.min(5,state.boss.teamStack+(id==='switchAll'?-2:id==='topLock'?-1:1)));if(state.boss.teamStack>=5)state.boss.beautifulTriggers++}state.phase='boss_clutch';save();render()}
  function growRolePlayer(){const rank={S:5,A:4,B:3,C:2,D:1},candidates=state.roster.filter(p=>['ROLE','STARTER'].includes(p.cardQuality||p.tier)).sort((a,b)=>(rank[b.potential]||0)-(rank[a.potential]||0));const p=candidates[0];if(!p)return null;const next=Y.addStarXp(H,p,1,'Boss关键对位');replacePlayer(next,'关键时段完成高质量对位，获得1成长进度');return p.id}
  function thirdStarEarned(boss){const rule=boss.star3;if(rule.type==='noLegend')return state.roster.every(x=>(x.cardQuality||x.tier)!=='LEGEND');if(rule.type==='noLegendCenter')return state.starterIds.map(player).filter(Boolean).every(x=>!x.positions.includes('C')||(x.cardQuality||x.tier)!=='LEGEND');if(rule.type==='twoCommonStarters')return state.starterIds.map(player).filter(Boolean).filter(x=>['ROLE','STARTER'].includes(x.cardQuality||x.tier)).length>=2;if(rule.type==='strategy')return state.boss.strategy===rule.id;if(rule.type==='combo')return state.boss.strategy===rule.strategy&&state.boss.mid===rule.mid;return false}
  function chooseClutch(id){const boss=currentBoss(),choice=boss.clutchChoices.find(x=>x.id===id);if(!choice)return;const t=team(),rng=V.rngFor(state.seed,`conquest_${boss.id}_finish`,state.boss.attempt),strategy=boss.strategies.find(x=>x.id===state.boss.strategy),mid=boss.midChoices.find(x=>x.id===state.boss.mid),intel=bossIntel(boss.id)*.017,scoreEdge=(state.boss.own-state.boss.opp)*.014;if(boss.id==='spurs14'){state.boss.teamStack=Math.max(0,Math.min(5,state.boss.teamStack+(id==='smallSwitch'?-2:id==='extraPass'?1:0)));if(state.boss.teamStack>=5)state.boss.beautifulTriggers++}let chance=H.clamp(.49+(t.power-boss.power)*.026+choiceBonus(strategy,t)+choiceBonus(mid,t)+choiceBonus(choice,t)+intel+scoreEdge,.12,.90);if(boss.id==='spurs14')chance-=state.boss.beautifulTriggers*.055;const won=rng()<chance;state.boss.clutch=id;state.boss.clutchFit=choiceFits(choice,t);state.runAttemptsByBoss[boss.id]=bossAttempts(boss.id)+1;let own=state.boss.own+Math.round(23+(t.offense-82)*.16+(choice.ownFinal||0)+(rng()-.5)*7),opp=state.boss.opp+Math.round(23-(t.defense-82)*.13+(choice.oppFinal||0)+(boss.number-1)*.45+(rng()-.5)*7);if(won&&own<=opp)own=opp+Math.ceil(2+rng()*5);if(!won&&own>=opp)opp=own+Math.ceil(2+rng()*5);Object.assign(state.boss,{own,opp,won});const p=progress(),record=p.bosses[boss.id];record.attempts++;if(won){const star2=boss.id==='rockets95'?state.boss.hakeemPoints<30:boss.id==='spurs14'?state.boss.beautifulTriggers<=1:opp<=boss.star2Max;state.boss.stars=1+(star2?1:0)+(thirdStarEarned(boss)?1:0);record.cleared=true;record.stars=Math.max(record.stars,state.boss.stars);record.bestScore=!record.bestScore||own-opp>record.bestScore.own-record.bestScore.opp?{own,opp}:record.bestScore;if(rng()<.65)state.boss.growthPlayerId=growRolePlayer()}else{state.intelByBoss[boss.id]=Math.min(2,bossIntel(boss.id)+1);state.adversity=Math.min(3,state.adversity+1);if(state.runAttemptsByBoss[boss.id]<=2)state.trainingPoints++}saveProgress(p);state.phase='boss_result';save();render()}
  function openReward(){state.phase='reward';save();render()}
  function afterReward(){state.rewardOffer=[];if(currentBoss().id==='pistons04'&&!state.routeChoices.length)state.phase='route_choice';else state.phase='hub'}
  function rewardPack(){const boss=currentBoss(),profiles=Y.createProfiles(H,V),pool=Y.playerPool(H).filter(p=>p.tags.some(tag=>boss.rewardTags.includes(tag))),rng=V.rngFor(state.seed,`${boss.id}_reward_pack`,progress().bosses[boss.id].attempts);state.rewardOffer=H.sample(pool,Math.min(3,pool.length),rng).map(p=>Y.cardFrom(H,V,p,profiles));state.phase='reward_player';save();render()}
  function chooseReward(type){state.rewardStats[type]=(state.rewardStats[type]||0)+1;if(type==='training'){state.trainingPoints+=2;afterReward()}else if(type==='budget'){state.budget+=2;afterReward()}else if(type==='upgrade'){state.phase='reward_upgrade'}else if(type==='hex'){const ids=Object.keys(Y.PLAYER_HEXES).filter(id=>id!=='mortal_to_god'||currentBoss().id==='spurs14'),rng=V.rngFor(state.seed,`${currentBoss().id}_hex`,bossAttempts()),gold=ids.filter(id=>Y.PLAYER_HEXES[id].quality==='GOLD');state.hexOffer=state.directRiskBonus&&currentBoss().id==='rockets95'?[gold[Math.floor(rng()*gold.length)],...H.sample(ids.filter(id=>!gold.includes(id)),2,rng)]:H.sample(ids,3,rng);state.phase='reward_hex'}else return rewardPack();save();render()}
  function chooseRewardPlayer(id){const p=state.rewardOffer.find(x=>x.id===id);if(!p)return;const existing=state.roster.find(x=>Y.duplicateKey(x)===Y.duplicateKey(p));if(existing){state.pendingDuplicateId=existing.id;if(existing.stars>=3){const result=Y.resolveDuplicate(H,existing,'training');state.trainingPoints+=result.trainingPoints;state.duplicateStats.training++;state.growthFeedback={type:'duplicate',title:'重复卡自动分解',name:existing.name,detail:'训练点 +2',description:'该球员已经达到★★★'};afterReward()}else state.phase='duplicate';save();return render()}if(!Y.canAdd(state.roster,p,state.budget))return toast(state.roster.length>=8?'阵容已经满8人，可将卡转为训练点':'王朝预算不足，可选择其他奖励');state.roster.push(p);afterReward();save();render()}
  function resolveDuplicate(choice){const existing=state.roster.find(x=>x.id===state.pendingDuplicateId);if(!existing)return;const result=Y.resolveDuplicate(H,existing,choice);state.trainingPoints+=result.trainingPoints;state.duplicateStats[result.converted]++;replacePlayer(result.player,'重复卡转化为1成长进度');state.pendingDuplicateId=null;afterReward();save();render()}
  function openTraining(){if(state.trainingPoints<2)return toast('至少需要2训练点');state.trainingTargetId=null;state.trainingPath=null;state.phase='training';save();render()}
  function chooseTrainingTarget(id){if(!state.freeTraining&&state.trainingPoints<2)return;state.trainingTargetId=id;state.phase='training_path';save();render()}
  function chooseTrainingPath(id){if(!Y.TRAINING_PATHS[id])return;state.trainingPath=id;state.phase='training_confirm';save();render()}
  function confirmTraining(){const index=state.roster.findIndex(p=>p.id===state.trainingTargetId);if(index<0||(!state.freeTraining&&state.trainingPoints<2))return;const before=state.roster[index],path=state.trainingPath,config=Y.TRAINING_PATHS[path],rng=V.rngFor(state.seed,`training_${before.id}`,before.training.length),next=Y.trainPlayer(before,path,H,rng);if(!state.freeTraining)state.trainingPoints-=2;replacePlayer(next,`${config.name}完成`);const camp=state.freeTraining;state.freeTraining=false;state.trainingTargetId=null;state.trainingPath=null;if(!state.growthFeedback)state.growthFeedback={type:'training',title:'训练完成',name:next.name,detail:config.name,description:'获得1成长进度'};state.phase=camp?'boss_brief':'hub';if(camp)state.currentBossId='rockets95';save();render()}
  function chooseRoute(id){state.routeChoices.push(id);state.directRiskBonus=id==='direct';if(id==='direct')openBoss('rockets95');else{state.freeTraining=true;state.phase='training';save();render()}}
  function chooseUpgradeTarget(id){const p=state.roster.find(x=>x.id===id);if(!p)return;replacePlayer(Y.addStarXp(H,p,1,'Boss升级奖励'),'Boss奖励提供1成长进度');afterReward();save();render()}
  function chooseHex(id){state.pendingHexId=id;state.phase='reward_hex_target';save();render()}
  function chooseHexTarget(id){const p=state.roster.find(x=>x.id===id),result=Y.applyPlayerHex(H,p,state.pendingHexId);if(result.status!=='applied')return toast('该球员不符合这个海克斯条件');replacePlayer(result.player,Y.PLAYER_HEXES[state.pendingHexId].name);state.playerHexIds.push(state.pendingHexId);state.pendingHexId=null;afterReward();save();render()}

  function fitLabel(choice,t){const good=choiceFits(choice,t);return`<em class="fit ${good?'good':''}">阵容适配：${good?'高':'一般'}</em>`}
  function renderChoice(choice,type,t){return`<button class="choice-btn" data-${type}="${choice.id}"><strong>${choice.title}</strong><span>${choice.description}</span>${fitLabel(choice,t)}</button>`}
  function renderHome(){const hasRun=state.selectedTeam&&state.roster.length;return`<section class="panel"><div class="hero"><div class="eyebrow">V0.3 · 历史征服</div><h1>穿越NBA历史<br>击败冠军王朝</h1><p>开启5张混合品质球员卡，在单局内培养阵容，并用真实篮球策略挑战各时代传奇球队。</p><div class="conquest-intro"><span><b>5张</b>初始球员卡</span><span><b>30点</b>王朝预算</span><span><b>3支</b>当前可玩Boss</span></div><div class="hero-actions"><button class="primary" data-new>开始历史征服</button>${hasRun?'<button class="ghost" data-continue>继续本轮征服</button>':''}<a class="ghost" href="./hex.html">返回海克斯王朝</a></div></div><p class="save-note">历史征服使用独立本地存档，不会覆盖王朝赛季或总经理模式。</p></section>`}
  function renderTeamSelect(){const groups=[['EAST','东部联盟'],['WEST','西部联盟']];return`<section class="panel">${seedStrip()}<div class="section-head"><div><div class="eyebrow">选择球队身份</div><h2>以哪支球队开启征服</h2></div><span>只影响球队身份与报告</span></div>${groups.map(([conf,label])=>`<div class="team-group"><h3>${label}</h3><div class="team-select-grid">${X.teams.filter(t=>t.conference===conf).map(t=>`<button class="team-choice" data-team="${t.id}" style="--team-a:${t.colors[0]};--team-b:${t.colors[1]}">${teamMark(t)}<span><b>${t.chineseName}</b><small>${t.historicalTags.slice(0,2).join(' · ')}</small></span></button>`).join('')}</div></div>`).join('')}</section>`}
  function renderStarterPack(){return`<section class="panel">${seedStrip()}<div class="section-head"><div><div class="eyebrow">初始球员包 · 5张全部加入</div><h2>你的征服阵容</h2></div><span>至少1张优质首发或更高</span></div><p class="pack-note">品质决定基础层级，不代表最终上限。普通球员可以在这一局中升星和成长。</p><div class="starter-pack">${state.starterPack.map((p,i)=>card(p,{index:i})).join('')}</div><div class="budget-preview"><span>初始预算占用</span><b>${Y.budgetUsed(state.starterPack)} / ${state.budget}</b></div><div class="footer-actions"><button class="primary" data-accept>收下5张球员卡</button></div></section>`}
  function bossCard(boss,p){const record=p.bosses[boss.id],unlocked=B.isUnlocked(boss.id,p),status=record.cleared?'completed':unlocked?'unlocked':'locked',tag=record.cleared?'已征服':unlocked?'可以挑战':'尚未解锁',body=`<span>副本 ${boss.number} · 危险度 ${'★'.repeat(boss.danger)}</span><h3>${boss.shortName}</h3><p>${boss.mechanicDescription}</p><strong>Boss：${boss.bossName}</strong><small>${tag} · ${'★'.repeat(record.stars)}${'☆'.repeat(3-record.stars)} · ${record.attempts}次</small>`;return unlocked?`<button class="boss-card ${status}" data-boss="${boss.id}">${body}</button>`:`<article class="boss-card ${status}">${body}</article>`}
  function renderHub(){const club=X.teamById(state.selectedTeam),p=progress(),t=team(),chapters=[...new Set(B.BOSSES.map(b=>b.chapter))];return`<section class="panel">${seedStrip()}<div class="club-banner">${teamMark(club,'small')}<span><b>${club.chineseName}</b><small>阵容成熟度 ${t.power>=90?'★★★★':t.power>=86?'★★★':'★★'} · ${t.builds?.[0]?.name||'Build尚未成型'}</small></span></div>${hud()}${chapters.map(chapter=>`<div class="chapter"><div class="chapter-head"><div class="eyebrow">${chapter}</div><h2>历史副本地图</h2></div><div class="boss-grid">${B.BOSSES.filter(b=>b.chapter===chapter).map(b=>bossCard(b,p)).join('')}</div></div>`).join('')}<div class="roadmap-card"><span>后续章节</span><b>热火 · 凯尔特人 · 公牛 · 湖人 · 勇士</b><small>本轮先完成火箭与马刺，剩余5个Boss尚未开放。</small></div><div class="roster-ribbon">${state.roster.map(p=>`<span class="q-${p.cardQuality||p.tier}"><b>${p.name}</b><small>${Y.stars(p)} · ${p.cost}费</small></span>`).join('')}</div><div class="map-actions"><button class="ghost" data-training ${state.trainingPoints<2?'disabled':''}>球员训练（2点）</button><button class="ghost" data-roster-info>阵容能力 ${Math.round(t.power)}</button></div></section>`}
  function renderBossBrief(){const boss=currentBoss(),t=team(),intel=bossIntel(),icon={pistons04:'🛡',rockets95:'🏀',spurs14:'🔄'}[boss.id];return`<section class="panel">${seedStrip()}${hud()}<div class="boss-hero"><div class="eyebrow">HISTORICAL BOSS ${String(boss.number).padStart(2,'0')}</div><h1>${boss.chineseName}</h1><p>${boss.subtitle}</p></div><div class="boss-mechanic"><span>${icon} BOSS机制 · ${boss.theme}</span><h2>${boss.mechanicTitle}</h2><p>${boss.mechanicDescription}</p></div><div class="boss-roster">${boss.roster.map(([name,pos])=>`<article class="boss-player"><b>${name}</b><span>${pos}</span></article>`).join('')}</div><div class="star-goals"><span>三星目标</span><b>① 击败Boss　② ${boss.star2Description||`对手不超过${boss.star2Max}分`}　③ ${boss.star3.description}</b></div><div class="section-head"><div><div class="eyebrow">赛前策略</div><h2>制定针对方案</h2></div><span>你的阵容能力 ${Math.round(t.power)}</span></div><div class="strategy-grid">${boss.strategies.map(x=>renderChoice(x,'strategy',t)).join('')}</div>${intel?`<div class="intel"><b>已解锁Boss情报：</b>${boss.intel[intel-1]}</div>`:''}</section>`}
  function renderBossMid(){const boss=currentBoss(),t=team(),dynamic=boss.id==='rockets95'?(state.boss.hakeemPoints>=22?`⚠️ 奥拉朱旺半场已经得到 ${state.boss.hakeemPoints} 分，单防正在失效。`:`⚠️ 火箭外线已命中 ${state.boss.rocketThrees} 记三分，包夹后的轮转出现漏洞。`):boss.id==='spurs14'?`⚠️ 马刺 TEAM STACK ${state.boss.teamStack}/5，达到5层将触发 Beautiful Game。`:boss.midAlert;return`<section class="panel">${seedStrip()}<div class="scoreboard"><div><span>你的球队</span><b>${state.boss.own}</b></div><em>半场</em><div><span>${boss.shortName}</span><b>${state.boss.opp}</b></div></div><p class="boss-alert">${dynamic}</p><div class="section-head"><div><div class="eyebrow">比赛中事件</div><h2>${boss.midTitle}</h2></div><span>选择会影响末节局势</span></div><div class="decision-grid">${boss.midChoices.map(x=>renderChoice(x,'mid',t)).join('')}</div></section>`}
  function renderBossClutch(){const boss=currentBoss(),t=team(),behind=state.boss.own<state.boss.opp;return`<section class="panel">${seedStrip()}<div class="scoreboard"><div><span>你的球队</span><b>${state.boss.own}</b></div><em>第三节结束</em><div><span>${boss.shortName}</span><b>${state.boss.opp}</b></div></div><p class="boss-alert">${behind?boss.clutchBehind:boss.clutchLead}</p><div class="section-head"><div><div class="eyebrow">第四节决策</div><h2>最后12分钟</h2></div><span>决定胜负</span></div><div class="decision-grid">${boss.clutchChoices.map(x=>renderChoice(x,'clutch',t)).join('')}</div></section>`}
  function renderBossResult(){const boss=currentBoss(),b=state.boss,growth=b.growthPlayerId&&player(b.growthPlayerId),rewardLabel=boss.number===B.BOSSES.length?'领取战利品并查看地图':'选择战利品';return`<section class="panel">${seedStrip()}<div class="result-hero ${b.won?'':'loss'}"><span>${b.won?'BOSS CLEARED':'CHALLENGE FAILED'}</span><h1>${b.own}-${b.opp}</h1><b>${b.won?boss.winText:boss.lossText}</b></div>${growth?`<article class="story-card"><span>成长事件 · 证明自己</span><b>${growth.season} ${growth.name}</b><p>在Boss战中完成关键对位，防守与成长进度获得提升。</p></article>`:''}${b.won?`<div class="boss-mechanic"><span>本次评价</span><h2>${'★'.repeat(b.stars)}${'☆'.repeat(3-b.stars)}</h2><p>击败Boss${b.opp<=boss.star2Max?` · 对手不超过${boss.star2Max}分`:''}${thirdStarEarned(boss)?` · ${boss.star3.description}`:''}</p></div><div class="footer-actions"><button class="primary" data-loot>${rewardLabel}</button></div>`:`<div class="intel"><b>失败收益：</b>Boss情报已更新${state.runAttemptsByBoss[boss.id]<=2?'，获得1训练点':''}，逆境点增加。你可以立即重试，也可以返回地图训练球员。</div><div class="footer-actions"><button class="primary" data-retry>重新挑战</button><button class="ghost" data-hub>返回征服地图</button></div>`}</section>`}
  function renderReward(){const boss=currentBoss(),risks=diagnosis();return`<section class="panel">${seedStrip()}<div class="section-head"><div><div class="eyebrow">${boss.shortName}战利品 · 五选一</div><h2>这次胜利怎样改变Build</h2></div><span>只能选择一项</span></div>${risks.length?`<div class="diagnosis"><b>阵容风险</b>${risks.map(x=>`<span>${x}</span>`).join('')}</div>`:''}<div class="reward-grid phase2-rewards"><button class="reward-card" data-reward="training"><span>稳定成长</span><h3>训练点 +2</h3><p>你有${state.roster.filter(p=>['A','S'].includes(p.potential)).length}名A/S潜力球员可培养。</p></button><button class="reward-card" data-reward="player"><span>${boss.theme}掉落</span><h3>${boss.rewardName}</h3><p>${boss.rewardDescription}</p></button><button class="reward-card" data-reward="budget"><span>阵容空间</span><h3>王朝预算 +2</h3><p>当前剩余预算 ${state.budget-Y.budgetUsed(state.roster)}。</p></button><button class="reward-card" data-reward="upgrade"><span>核心培养</span><h3>球员成长 +1</h3><p>指定现有球员推进升星。</p></button><button class="reward-card" data-reward="hex"><span>改变路线</span><h3>球员型海克斯</h3><p>从3个培养效果中选择1个。</p></button></div></section>`}
  function renderRewardPlayer(){const boss=currentBoss();return`<section class="panel">${seedStrip()}${hud()}<div class="section-head"><div><div class="eyebrow">${boss.rewardName}</div><h2>选择一张球员卡</h2></div><span>受8人上限与预算限制</span></div><div class="content v03-offer">${state.rewardOffer.map((p,i)=>card(p,{action:'reward-player',index:i})).join('')}</div></section>`}
  function renderRouteChoice(){return`<section class="panel">${seedStrip()}<div class="section-head"><div><div class="eyebrow">ROUTE CHOICE · 首次分叉</div><h2>活塞之后，下一步怎么走</h2></div><span>选择会影响成长速度</span></div><div class="diagnosis"><b>当前阵容风险</b>${diagnosis().map(x=>`<span>${x}</span>`).join('')||'<span>阵容较均衡</span>'}</div><div class="route-choice-grid"><button class="route-choice risky" data-route="direct"><span>高风险 · 高奖励</span><h3>直接挑战1995火箭</h3><p>立刻挑战超级内线与包夹惩罚；胜利追加1个金色海克斯候选。</p></button><button class="route-choice" data-route="camp"><span>稳定成长</span><h3>进入训练营</h3><p>获得一次免费训练，但放弃直接挑战的额外高阶奖励。</p></button></div></section>`}
  function renderTraining(){return`<section class="panel">${seedStrip()}${hud()}<div class="section-head"><div><div class="eyebrow">${state.freeTraining?'路线奖励 · 免费训练':'球员训练 · 消耗2点'}</div><h2>先选择培养球员</h2></div><span>星级与品质互相独立</span></div><div class="content v03-offer">${state.roster.map((p,i)=>card(p,{action:'training-target',index:i})).join('')}</div></section>`}
  function renderTrainingPath(){const p=player(state.trainingTargetId);return`<section class="panel">${seedStrip()}<div class="section-head"><div><div class="eyebrow">培养 ${p.name}</div><h2>选择训练方向</h2></div><span>${p.potential}潜力 · 收益×${Y.POTENTIAL_MULTIPLIER[p.potential]}</span></div><div class="training-grid">${Object.entries(Y.TRAINING_PATHS).map(([id,x])=>`<button class="training-card" data-training-path="${id}"><strong>${x.name}</strong><span>${x.description}</span></button>`).join('')}</div></section>`}
  function renderTrainingConfirm(){const p=player(state.trainingTargetId),x=Y.trainingPreview(p,state.trainingPath),rows=[...Object.entries(x.attributes||{}),...Object.entries(x.hidden||{})];return`<section class="panel">${seedStrip()}<div class="training-preview"><span>训练预览</span><h2>${p.name} · ${x.name}</h2><p>${x.description}</p><div>${rows.map(([key,value])=>`<b>${key} +${Math.round(value*x.multiplier*10)/10}</b>`).join('')}<b>成长进度 +1</b></div></div><div class="footer-actions"><button class="primary" data-confirm-training>确认训练</button><button class="ghost" data-back-path>重新选择</button></div></section>`}
  function renderDuplicate(){const p=player(state.pendingDuplicateId);return`<section class="panel">${seedStrip()}<div class="duplicate-hero"><span>DUPLICATE · 重复球员卡</span><h2>${p.season} ${p.name}</h2><p>同年份、同版本球员已在阵容中。重复卡不会浪费。</p></div><div class="route-choice-grid"><button class="route-choice" data-duplicate="growth"><span>继续培养</span><h3>成长进度 +1</h3><p>更快推动该球员升星。</p></button><button class="route-choice" data-duplicate="training"><span>资源回收</span><h3>训练点 +2</h3><p>把资源转移给阵容中的其他球员。</p></button></div></section>`}
  function renderUpgrade(){return`<section class="panel">${seedStrip()}<div class="section-head"><div><div class="eyebrow">Boss升级奖励</div><h2>选择获得1成长进度的球员</h2></div></div><div class="content v03-offer">${state.roster.filter(p=>p.stars<3).map((p,i)=>card(p,{action:'upgrade-target',index:i})).join('')}</div></section>`}
  function renderHex(){return`<section class="panel">${seedStrip()}<div class="section-head"><div><div class="eyebrow">球员型海克斯 · 三选一</div><h2>改变一名球员的成长路线</h2></div></div><div class="reward-grid">${state.hexOffer.map(id=>{const x=Y.PLAYER_HEXES[id];return`<button class="reward-card hex-${x.quality}" data-player-hex="${id}"><span>${x.quality}</span><h3>${x.name}</h3><p>${x.description}</p></button>`}).join('')}</div></section>`}
  function renderHexTarget(){const x=Y.PLAYER_HEXES[state.pendingHexId];return`<section class="panel">${seedStrip()}<div class="section-head"><div><div class="eyebrow">${x.name}</div><h2>选择作用球员</h2></div><span>${x.description}</span></div><div class="content v03-offer">${state.roster.map((p,i)=>card(p,{action:'hex-target',index:i})).join('')}</div></section>`}
  function growthOverlay(){const f=state.growthFeedback;if(!f)return'';const gains=f.gains?Object.entries(f.gains).filter(([,v])=>v).map(([k,v])=>`${k} +${v}`).join(' · '):'';return`<div class="growth-overlay"><div class="growth-modal ${f.type}"><span>${f.title}</span><h2>${f.name}</h2><strong>${f.detail}</strong><p>${f.description||''}</p>${gains?`<small>${gains}</small>`:''}<button class="primary" data-dismiss-growth>继续</button></div></div>`}

  function goHub(){state.phase='hub';save();render()}
  function contextBack(){if(['boss_brief','boss_mid','boss_clutch','boss_result','reward','reward_player','reward_upgrade','reward_hex','reward_hex_target','training','route_choice','duplicate'].includes(state.phase))state.phase='hub';else if(state.phase==='training_path')state.phase='training';else if(state.phase==='training_confirm')state.phase='training_path';else state.phase='home';save();render()}
  function updateTop(){const back=$('[data-context-back]'),secondary=state.phase!=='home';back?.classList.toggle('hidden',!secondary);if(back)back.onclick=contextBack}
  function render(){const views={home:renderHome,team_select:renderTeamSelect,starter_pack:renderStarterPack,hub:renderHub,boss_brief:renderBossBrief,boss_mid:renderBossMid,boss_clutch:renderBossClutch,boss_result:renderBossResult,reward:renderReward,reward_player:renderRewardPlayer,reward_upgrade:renderUpgrade,reward_hex:renderHex,reward_hex_target:renderHexTarget,route_choice:renderRouteChoice,duplicate:renderDuplicate,training:renderTraining,training_path:renderTrainingPath,training_confirm:renderTrainingConfirm},phaseChanged=renderedPhase!==state.phase;$('#screen').innerHTML=(views[state.phase]||renderHome)()+growthOverlay();updateTop();bind();if(phaseChanged){renderedPhase=state.phase;window.scrollTo({top:0,left:0,behavior:'instant'})}}
  function bind(){document.querySelectorAll('[data-new]').forEach(b=>b.addEventListener('click',startNew));$('[data-continue]')?.addEventListener('click',()=>{state.phase=state.phase==='home'?'hub':state.phase;render()});document.querySelectorAll('[data-team]').forEach(b=>b.addEventListener('click',()=>chooseTeam(b.dataset.team)));$('[data-accept]')?.addEventListener('click',acceptPack);document.querySelectorAll('[data-boss]').forEach(b=>b.addEventListener('click',()=>openBoss(b.dataset.boss)));document.querySelectorAll('[data-strategy]').forEach(b=>b.addEventListener('click',()=>beginBoss(b.dataset.strategy)));document.querySelectorAll('[data-mid]').forEach(b=>b.addEventListener('click',()=>chooseMid(b.dataset.mid)));document.querySelectorAll('[data-clutch]').forEach(b=>b.addEventListener('click',()=>chooseClutch(b.dataset.clutch)));$('[data-loot]')?.addEventListener('click',openReward);document.querySelectorAll('[data-reward]').forEach(b=>b.addEventListener('click',()=>chooseReward(b.dataset.reward)));document.querySelectorAll('[data-reward-player]').forEach(b=>b.addEventListener('click',()=>chooseRewardPlayer(b.dataset.rewardPlayer)));document.querySelectorAll('[data-route]').forEach(b=>b.addEventListener('click',()=>chooseRoute(b.dataset.route)));document.querySelectorAll('[data-duplicate]').forEach(b=>b.addEventListener('click',()=>resolveDuplicate(b.dataset.duplicate)));document.querySelectorAll('[data-upgrade-target]').forEach(b=>b.addEventListener('click',()=>chooseUpgradeTarget(b.dataset.upgradeTarget)));document.querySelectorAll('[data-player-hex]').forEach(b=>b.addEventListener('click',()=>chooseHex(b.dataset.playerHex)));document.querySelectorAll('[data-hex-target]').forEach(b=>b.addEventListener('click',()=>chooseHexTarget(b.dataset.hexTarget)));$('[data-retry]')?.addEventListener('click',()=>openBoss(currentBoss().id));$('[data-hub]')?.addEventListener('click',goHub);$('[data-training]')?.addEventListener('click',openTraining);document.querySelectorAll('[data-training-path]').forEach(b=>b.addEventListener('click',()=>chooseTrainingPath(b.dataset.trainingPath)));document.querySelectorAll('[data-training-target]').forEach(b=>b.addEventListener('click',()=>chooseTrainingTarget(b.dataset.trainingTarget)));$('[data-confirm-training]')?.addEventListener('click',confirmTraining);$('[data-back-path]')?.addEventListener('click',()=>{state.phase='training_path';render()});$('[data-dismiss-growth]')?.addEventListener('click',()=>{state.growthFeedback=null;save();render()});$('[data-roster-info]')?.addEventListener('click',()=>toast(`当前阵容能力 ${Math.round(team().power)}，预算 ${Y.budgetUsed(state.roster)}/${state.budget}`))}

  state=load();if(!['home','team_select','starter_pack','hub','boss_brief','boss_mid','boss_clutch','boss_result','reward','reward_player','reward_upgrade','reward_hex','reward_hex_target','route_choice','duplicate','training','training_path','training_confirm'].includes(state.phase))state.phase='home';render();
})();
