(function(){
  'use strict';
  const H=globalThis.HexEngine,V=globalThis.HexV02,X=globalThis.HexV022,Y=globalThis.HexV03,AVATARS=globalThis.HexPlayerAvatars||{};
  const STORAGE='nba_hex_conquest_v03',PROGRESS_STORAGE='nba_hex_conquest_progress_v03';
  const $=s=>document.querySelector(s),tierNames=Y.QUALITY_LABELS,positionNames={PG:'控卫',SG:'分卫',SF:'小前',PF:'大前',C:'中锋'},tagNames={shooting:'投射',creator:'持球创造',offball:'无球',playmaker:'组织',size:'体型',multi:'全能',defense:'防守',leader:'领袖',rebound:'篮板',slasher:'突破',clutch:'关键球',athletic:'运动能力',rim:'护框',post:'低位',bench:'替补'};
  const PISTONS={id:'pistons04',name:'2004 Detroit Pistons',chineseName:'2004 底特律活塞',theme:'铁桶防守',power:87,roster:[['昌西·比卢普斯','PG'],['理查德·汉密尔顿','SG'],['泰肖恩·普林斯','SF'],['拉希德·华莱士','PF'],['本·华莱士','C']]};
  let state=null,toastTimer=null,renderedPhase=null;

  function blank(seed=V.createSeed()){return{version:0.3,phase:'home',seed:V.normalizeSeed(seed),selectedTeam:null,roster:[],starterIds:[],coreIds:[],hexIds:[],budget:30,trainingPoints:0,adversity:0,intel:0,runAttempts:0,starterPack:[],boss:null,rewardOffer:[],trainingPath:null,startedAt:null}}
  function migrate(raw){const base=blank(raw?.seed);return Object.assign(base,raw||{},{roster:Array.isArray(raw?.roster)?raw.roster:[],starterIds:Array.isArray(raw?.starterIds)?raw.starterIds:[],coreIds:Array.isArray(raw?.coreIds)?raw.coreIds:[],hexIds:Array.isArray(raw?.hexIds)?raw.hexIds:[],starterPack:Array.isArray(raw?.starterPack)?raw.starterPack:[],rewardOffer:Array.isArray(raw?.rewardOffer)?raw.rewardOffer:[]})}
  function load(){try{const raw=localStorage.getItem(STORAGE);return raw?migrate(JSON.parse(raw)):blank()}catch{return blank()}}
  function save(){try{localStorage.setItem(STORAGE,JSON.stringify(state))}catch{}}
  function progress(){try{return Object.assign({pistons:{cleared:false,stars:0,attempts:0,bestScore:null}},JSON.parse(localStorage.getItem(PROGRESS_STORAGE)||'{}'))}catch{return{pistons:{cleared:false,stars:0,attempts:0,bestScore:null}}}}
  function saveProgress(data){try{localStorage.setItem(PROGRESS_STORAGE,JSON.stringify(data))}catch{}}
  function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').classList.add('on');toastTimer=setTimeout(()=>$('#toast').classList.remove('on'),1800)}
  function player(id){return state.roster.find(p=>p.id===id)||state.starterPack.find(p=>p.id===id)||state.rewardOffer.find(p=>p.id===id)||H.players.find(p=>p.id===id)}
  function team(){return V.enhancedTeam(H,state,false)}
  function teamMark(t,size=''){const code=t.abbreviation||t.id;return`<span class="team-mark ${size}" style="--team-a:${t.colors?.[0]||'#39d9ff'};--team-b:${t.colors?.[1]||'#f5f7fb'}"><span>${code}</span><img src="./assets/team-logos/${code}.svg" alt="" loading="lazy" decoding="async" onerror="this.remove()"></span>`}
  function avatar(p,size=''){const src=AVATARS[p.id],short=p.name.replace(/[·-]/g,'').slice(-2);return`<span class="player-avatar ${size}" aria-hidden="true"><span>${short}</span>${src?`<img src="${src}" alt="" loading="lazy" decoding="async" onerror="this.remove()">`:''}</span>`}
  function identity(p){return`<span class="player-identity">${avatar(p)}<span><b>${p.name}</b><small>${p.season} · ${p.age}岁</small></span></span>`}
  function card(p,{action='',index=0}={}){const tag=p.tags.slice(0,3).map(x=>tagNames[x]||x).join(' · '),open=action?'button':'article',close=open==='button'?'button':'article',attr=action?`data-${action}="${p.id}"`:'';return`<${open} class="v03-player-card q-${p.cardQuality||p.tier}" ${attr} style="--deal:${index*.08}s"><span class="card-quality">${tierNames[p.cardQuality||p.tier]||p.tier}</span><span class="card-year">${p.season}</span>${identity(p)}<p>${p.positions.map(x=>positionNames[x]||x).join(' / ')} · ${tag}</p><div class="card-rating"><span>能力<strong>${p.currentRating||Math.round(H.playerOff(p))}</strong></span><span>潜力<strong>${p.potential||'—'}</strong></span><span>费用<strong>${p.cost||'—'}</strong></span></div><div class="card-stars">${Y.stars(p)}</div></${close}>`}
  function seedStrip(){return`<div class="seed-strip"><span class="mode-chip">历史征服</span><span>本局Seed <b>${state.seed}</b></span></div>`}
  function hud(){const p=progress();return`<div class="conquest-hud"><span>已征服 <b>${p.pistons.cleared?1:0}/8</b></span><span>星星 <b>${p.pistons.stars}/24</b></span><span>预算 <b>${Y.budgetUsed(state.roster)}/${state.budget}</b></span><span>训练点 <b>${state.trainingPoints}</b></span><span>逆境点 <b>${state.adversity}/3</b></span></div>`}

  function startNew(){state=blank();state.phase='team_select';state.startedAt=Date.now();save();render()}
  function chooseTeam(id){const club=X.teamById(id);if(!club)return;state.selectedTeam=id;state.starterPack=Y.initialPack(H,V,state.seed);state.phase='starter_pack';save();render()}
  function acceptPack(){state.roster=state.starterPack.map(p=>({...p,positions:[...p.positions],attributes:{...p.attributes},hidden:{...p.hidden},tags:[...p.tags]}));state.starterIds=state.roster.map(p=>p.id);state.coreIds=[...state.roster].sort((a,b)=>H.playerOff(b)-H.playerOff(a)).slice(0,3).map(p=>p.id);state.phase='hub';save();render()}
  function openBoss(){state.phase='boss_brief';save();render()}
  const strategyMod=id=>({share:.055,space:.035,rebound:.03}[id]||0);
  function beginBoss(strategy){const t=team(),attempt=state.runAttempts+1,rng=V.rngFor(state.seed,'conquest_pistons_half',attempt),edge=t.power-PISTONS.power,own=Math.round(50+edge*.45+strategyMod(strategy)*35+(rng()-.5)*9),opp=Math.round(51+(rng()-.5)*8);state.boss={id:PISTONS.id,strategy,mid:null,clutch:null,attempt,own,opp,won:null,growthPlayerId:null,stars:0};state.phase='boss_mid';save();render()}
  function chooseMid(id){const t=team(),rng=V.rngFor(state.seed,'conquest_pistons_third',state.boss.attempt),mods={second:[t.playmaking>=84?6:3,-1],fiveout:[t.space>=86?7:2,1],physical:[t.defense>=84&&t.rebound>=82?4:1,-4]}[id]||[2,0];state.boss.mid=id;state.boss.own+=Math.round(25+mods[0]+(rng()-.5)*6);state.boss.opp+=Math.round(24+mods[1]+(rng()-.5)*6);state.phase='boss_clutch';save();render()}
  function growRolePlayer(){const candidates=state.roster.filter(p=>['ROLE','STARTER'].includes(p.cardQuality||p.tier)).sort((a,b)=>({S:5,A:4,B:3,C:2,D:1}[b.potential]-({S:5,A:4,B:3,C:2,D:1}[a.potential])));const p=candidates[0];if(!p)return null;p.growth=(p.growth||0)+1;p.attributes.perimeterDefense=Math.min(99,p.attributes.perimeterDefense+2);p.currentRating=Math.min(99,(p.currentRating||70)+1);if(p.growth>=2&&p.stars<3){p.stars++;p.growth=0;p.cost=Math.min(7,p.cost+1)}return p.id}
  function chooseClutch(id){const t=team(),rng=V.rngFor(state.seed,'conquest_pistons_finish',state.boss.attempt),mods={rotation:.035,weakside:.04,defense:.03},intel=Math.min(2,state.intel)*.018,scoreEdge=(state.boss.own-state.boss.opp)*.018,chance=H.clamp(.52+(t.power-PISTONS.power)*.028+strategyMod(state.boss.strategy)+(mods[id]||0)+intel+scoreEdge,.16,.90),won=rng()<chance;state.boss.clutch=id;state.runAttempts++;let own=state.boss.own+Math.round(24+(t.offense-82)*.18+(rng()-.5)*7),opp=state.boss.opp+Math.round(23-(t.defense-82)*.14+(rng()-.5)*7);if(won&&own<=opp)own=opp+Math.ceil(2+rng()*6);if(!won&&own>=opp)opp=own+Math.ceil(2+rng()*6);state.boss.own=own;state.boss.opp=opp;state.boss.won=won;const p=progress();p.pistons.attempts++;if(won){state.boss.stars=1+(opp<=105?1:0)+(state.roster.every(x=>(x.cardQuality||x.tier)!=='LEGEND')?1:0);p.pistons.cleared=true;p.pistons.stars=Math.max(p.pistons.stars,state.boss.stars);p.pistons.bestScore=!p.pistons.bestScore||own-opp>p.pistons.bestScore.own-p.pistons.bestScore.opp?{own,opp}:p.pistons.bestScore;if(rng()<.65)state.boss.growthPlayerId=growRolePlayer();}else{state.intel=Math.min(2,state.intel+1);state.adversity=Math.min(3,state.adversity+1);if(state.runAttempts<=2)state.trainingPoints++;}saveProgress(p);state.phase='boss_result';save();render()}
  function openReward(){state.phase='reward';save();render()}
  function rewardPack(){const profiles=Y.createProfiles(H,V),chosen=new Set(state.roster.map(p=>p.id)),pool=H.players.filter(p=>!chosen.has(p.id)&&(p.tags.includes('defense')||p.tags.includes('rebound')||p.tags.includes('playmaker'))),rng=V.rngFor(state.seed,'pistons_reward_pack',progress().pistons.attempts);state.rewardOffer=H.sample(pool,3,rng).map(p=>Y.cardFrom(H,V,p,profiles));state.phase='reward_player';save();render()}
  function chooseReward(type){if(type==='training'){state.trainingPoints+=2;state.phase='hub'}else if(type==='budget'){state.budget+=2;state.phase='hub'}else return rewardPack();save();render()}
  function chooseRewardPlayer(id){const p=state.rewardOffer.find(x=>x.id===id);if(!p)return;if(!Y.canAdd(state.roster,p,state.budget))return toast(state.roster.length>=8?'阵容已经满8人':'王朝预算不足，可选择其他奖励');state.roster.push(p);state.phase='hub';state.rewardOffer=[];save();render()}
  function openTraining(){if(state.trainingPoints<2)return toast('至少需要2训练点');state.phase='training';save();render()}
  function chooseTrainingPath(id){if(!Y.TRAINING_PATHS[id])return;state.trainingPath=id;state.phase='training_target';save();render()}
  function chooseTrainingTarget(id){const index=state.roster.findIndex(p=>p.id===id);if(index<0||state.trainingPoints<2)return;state.roster[index]=Y.trainPlayer(state.roster[index],state.trainingPath);state.trainingPoints-=2;state.trainingPath=null;state.phase='hub';save();render();toast(`${state.roster[index].name}完成训练`)}

  function renderHome(){const hasRun=state.selectedTeam&&state.roster.length;return`<section class="panel"><div class="hero"><div class="eyebrow">V0.3 · 副本优先开发版</div><h1>穿越NBA历史<br>击败冠军王朝</h1><p>开启5张混合品质球员卡，在单局内培养阵容、获取海克斯，并用真实篮球策略挑战各时代传奇球队。</p><div class="conquest-intro"><span><b>5张</b>初始球员卡</span><span><b>30点</b>王朝预算</span><span><b>最终Boss</b>2017勇士</span></div><div class="hero-actions"><button class="primary" data-new>开始历史征服</button>${hasRun?'<button class="ghost" data-continue>继续本轮征服</button>':''}<a class="ghost" href="./hex.html">返回海克斯王朝</a></div></div><p class="save-note">历史征服使用独立本地存档，不会覆盖王朝赛季或总经理模式。</p></section>`}
  function renderTeamSelect(){const groups=[['EAST','东部联盟'],['WEST','西部联盟']];return`<section class="panel">${seedStrip()}<div class="section-head"><div><div class="eyebrow">选择球队身份</div><h2>以哪支球队开启征服</h2></div><span>只影响球队身份与报告</span></div>${groups.map(([conf,label])=>`<div class="team-group"><h3>${label}</h3><div class="team-select-grid">${X.teams.filter(t=>t.conference===conf).map(t=>`<button class="team-choice" data-team="${t.id}" style="--team-a:${t.colors[0]};--team-b:${t.colors[1]}">${teamMark(t)}<span><b>${t.chineseName}</b><small>${t.historicalTags.slice(0,2).join(' · ')}</small></span></button>`).join('')}</div></div>`).join('')}</section>`}
  function renderStarterPack(){return`<section class="panel">${seedStrip()}<div class="section-head"><div><div class="eyebrow">初始球员包 · 5张全部加入</div><h2>你的征服阵容</h2></div><span>至少1张优质首发或更高</span></div><p class="pack-note">品质决定基础层级，不代表最终上限。普通球员可以在这一局中升星和成长。</p><div class="starter-pack">${state.starterPack.map((p,i)=>card(p,{index:i})).join('')}</div><div class="budget-preview"><span>初始预算占用</span><b>${Y.budgetUsed(state.starterPack)} / ${state.budget}</b></div><div class="footer-actions"><button class="primary" data-accept>收下5张球员卡</button></div></section>`}
  function renderHub(){const club=X.teamById(state.selectedTeam),p=progress(),t=team();return`<section class="panel">${seedStrip()}<div class="club-banner">${teamMark(club,'small')}<span><b>${club.chineseName}</b><small>阵容成熟度 ${t.power>=90?'★★★★':t.power>=86?'★★★':'★★'} · ${t.builds?.[0]?.name||'Build尚未成型'}</small></span></div>${hud()}<div class="chapter"><div class="chapter-head"><div class="eyebrow">第一章 · 铁血与内线</div><h2>历史副本地图</h2></div><div class="boss-grid"><button class="boss-card unlocked" data-boss><span>副本 1 · 危险度 ★★</span><h3>2004 活塞</h3><p>总决赛级铁桶防守，重点压制玩家第一核心。</p><strong>Boss：本·华莱士</strong><small>当前：${'★'.repeat(p.pistons.stars)}${'☆'.repeat(3-p.pistons.stars)} · ${p.pistons.attempts}次挑战</small></button><article class="boss-card final locked"><span>终章预览 · 危险度 ★★★★★★</span><h3>2017 勇士</h3><p>死亡五小、第三节攻击波和无限换防。</p><strong>最终Boss</strong><small>完成前置副本后开放</small></article></div></div><div class="roster-ribbon">${state.roster.map(p=>`<span class="q-${p.cardQuality||p.tier}"><b>${p.name}</b><small>${Y.stars(p)} · ${p.cost}费</small></span>`).join('')}</div><div class="map-actions"><button class="ghost" data-training ${state.trainingPoints<2?'disabled':''}>球员训练（2点）</button><button class="ghost" data-roster-info>阵容能力 ${Math.round(t.power)}</button></div></section>`}
  function renderBossBrief(){const t=team();return`<section class="panel">${seedStrip()}${hud()}<div class="boss-hero"><div class="eyebrow">HISTORICAL BOSS 01</div><h1>${PISTONS.chineseName}</h1><p>总决赛冠军 · 防守效率时代标杆</p></div><div class="boss-mechanic"><span>BOSS机制</span><h2>禁止得分</h2><p>活塞会额外针对你的第一核心，并强化护框与篮板。只依赖一个超级得分手很难过关。</p></div><div class="boss-roster">${PISTONS.roster.map(([name,pos])=>`<article class="boss-player"><b>${name}</b><span>${pos}</span></article>`).join('')}</div><div class="section-head"><div><div class="eyebrow">赛前策略</div><h2>怎样拆解铁桶防守</h2></div><span>你的阵容能力 ${Math.round(t.power)}</span></div><div class="strategy-grid"><button class="choice-btn" data-strategy="share"><strong>让第二核心发起</strong><span>分散第一核心压力，组织能力越强收益越高。</span></button><button class="choice-btn" data-strategy="space"><strong>五外拉开禁区</strong><span>依靠投射把本·华莱士带离篮筐。</span></button><button class="choice-btn" data-strategy="rebound"><strong>先保护篮板</strong><span>降低活塞二次进攻，拖入稳定的半场比赛。</span></button></div>${state.intel?`<div class="intel"><b>已解锁Boss情报：</b>${state.intel>=2?'活塞会优先夹击第一核心；弱侧出球和第二组织点能够明显降低压力。':'他们的半场防守极强，但比赛节奏较慢。'}</div>`:''}</section>`}
  function renderBossMid(){return`<section class="panel">${seedStrip()}<div class="scoreboard"><div><span>你的球队</span><b>${state.boss.own}</b></div><em>半场</em><div><span>2004 活塞</span><b>${state.boss.opp}</b></div></div><p class="boss-alert">活塞开始夹击你的第一核心，普林斯正在切断强侧传球路线。</p><div class="section-head"><div><div class="eyebrow">比赛中事件</div><h2>第三节如何调整</h2></div><span>选择会影响末节局势</span></div><div class="decision-grid"><button class="choice-btn" data-mid="second"><strong>第二核心持球</strong><span>考验阵容组织，减少第一核心强攻。</span></button><button class="choice-btn" data-mid="fiveout"><strong>增加五外回合</strong><span>空间越好，越容易惩罚收缩防守。</span></button><button class="choice-btn" data-mid="physical"><strong>提升对抗强度</strong><span>用防守和篮板把比分咬住。</span></button></div></section>`}
  function renderBossClutch(){const behind=state.boss.own<state.boss.opp;return`<section class="panel">${seedStrip()}<div class="scoreboard"><div><span>你的球队</span><b>${state.boss.own}</b></div><em>第三节结束</em><div><span>2004 活塞</span><b>${state.boss.opp}</b></div></div><p class="boss-alert">${behind?'你在进入第四节时落后，必须主动改变比赛。':'活塞仍在等待你的第一核心陷入单打，领先优势并不安全。'}</p><div class="section-head"><div><div class="eyebrow">第四节决策</div><h2>最后12分钟</h2></div><span>决定胜负</span></div><div class="decision-grid"><button class="choice-btn" data-clutch="rotation"><strong>缩短轮换</strong><span>提高核心球员权重，但会承担体能风险。</span></button><button class="choice-btn" data-clutch="weakside"><strong>持续攻击弱侧</strong><span>利用夹击后的空位，考验传球与投射。</span></button><button class="choice-btn" data-clutch="defense"><strong>摆出防守阵容</strong><span>降低双方得分，依靠关键回合过关。</span></button></div></section>`}
  function renderBossResult(){const b=state.boss,growth=b.growthPlayerId&&player(b.growthPlayerId);return`<section class="panel">${seedStrip()}<div class="result-hero ${b.won?'':'loss'}"><span>${b.won?'BOSS CLEARED':'CHALLENGE FAILED'}</span><h1>${b.own}-${b.opp}</h1><b>${b.won?'击败2004底特律活塞':'铁桶防守守住了比赛'}</b></div>${growth?`<article class="story-card"><span>成长事件 · 证明自己</span><b>${growth.season} ${growth.name}</b><p>在Boss战中完成关键对位，防守与成长进度获得提升。</p></article>`:''}${b.won?`<div class="boss-mechanic"><span>本次评价</span><h2>${'★'.repeat(b.stars)}${'☆'.repeat(3-b.stars)}</h2><p>击败Boss ${b.stars>=2?'· 将对手限制在105分以内 ':''}${b.stars>=3?'· 无LEGEND通关':''}</p></div><div class="footer-actions"><button class="primary" data-loot>选择战利品</button></div>`:`<div class="intel"><b>失败收益：</b>Boss情报已更新${state.runAttempts<=2?'，获得1训练点':''}，逆境点增加。你可以立即重试，也可以返回地图训练球员。</div><div class="footer-actions"><button class="primary" data-retry>重新挑战</button><button class="ghost" data-hub>返回征服地图</button></div>`}</section>`}
  function renderReward(){return`<section class="panel">${seedStrip()}<div class="section-head"><div><div class="eyebrow">BOSS战利品 · 三选一</div><h2>这次胜利怎样改变Build</h2></div><span>只能选择一项</span></div><div class="reward-grid"><button class="reward-card" data-reward="training"><span>稳定成长</span><h3>训练点 +2</h3><p>培养现有球员，推进升星与属性成长。</p></button><button class="reward-card" data-reward="player"><span>活塞掉落</span><h3>防守球员包</h3><p>从3张防守、篮板或组织型球员卡中选择1张。</p></button><button class="reward-card" data-reward="budget"><span>阵容空间</span><h3>王朝预算 +2</h3><p>为后续高费用球员和升星培养留下空间。</p></button></div></section>`}
  function renderRewardPlayer(){return`<section class="panel">${seedStrip()}${hud()}<div class="section-head"><div><div class="eyebrow">活塞防守球员包</div><h2>选择一张球员卡</h2></div><span>受8人上限与预算限制</span></div><div class="content v03-offer">${state.rewardOffer.map((p,i)=>card(p,{action:'reward-player',index:i})).join('')}</div></section>`}
  function renderTraining(){return`<section class="panel">${seedStrip()}${hud()}<div class="section-head"><div><div class="eyebrow">球员训练 · 消耗2点</div><h2>选择训练方向</h2></div><span>高潜力球员收益更高</span></div><div class="training-grid">${Object.entries(Y.TRAINING_PATHS).map(([id,x])=>`<button class="training-card" data-training-path="${id}"><strong>${x.name}</strong><span>${x.description}</span></button>`).join('')}</div></section>`}
  function renderTrainingTarget(){const x=Y.TRAINING_PATHS[state.trainingPath];return`<section class="panel">${seedStrip()}${hud()}<div class="section-head"><div><div class="eyebrow">${x.name}</div><h2>选择培养球员</h2></div><span>训练后返回征服地图</span></div><div class="content v03-offer">${state.roster.map((p,i)=>card(p,{action:'training-target',index:i})).join('')}</div></section>`}

  function goHub(){state.phase='hub';save();render()}
  function contextBack(){if(['boss_brief','boss_mid','boss_clutch','boss_result','reward','reward_player','training'].includes(state.phase))state.phase='hub';else if(state.phase==='training_target')state.phase='training';else state.phase='home';save();render()}
  function updateTop(){const back=$('[data-context-back]'),secondary=state.phase!=='home';back?.classList.toggle('hidden',!secondary);if(back)back.onclick=contextBack}
  function render(){const views={home:renderHome,team_select:renderTeamSelect,starter_pack:renderStarterPack,hub:renderHub,boss_brief:renderBossBrief,boss_mid:renderBossMid,boss_clutch:renderBossClutch,boss_result:renderBossResult,reward:renderReward,reward_player:renderRewardPlayer,training:renderTraining,training_target:renderTrainingTarget},phaseChanged=renderedPhase!==state.phase;$('#screen').innerHTML=(views[state.phase]||renderHome)();updateTop();bind();if(phaseChanged){renderedPhase=state.phase;window.scrollTo({top:0,left:0,behavior:'instant'})}}
  function bind(){document.querySelectorAll('[data-new]').forEach(b=>b.addEventListener('click',startNew));$('[data-continue]')?.addEventListener('click',()=>{state.phase=state.phase==='home'?'hub':state.phase;render()});document.querySelectorAll('[data-team]').forEach(b=>b.addEventListener('click',()=>chooseTeam(b.dataset.team)));$('[data-accept]')?.addEventListener('click',acceptPack);$('[data-boss]')?.addEventListener('click',openBoss);document.querySelectorAll('[data-strategy]').forEach(b=>b.addEventListener('click',()=>beginBoss(b.dataset.strategy)));document.querySelectorAll('[data-mid]').forEach(b=>b.addEventListener('click',()=>chooseMid(b.dataset.mid)));document.querySelectorAll('[data-clutch]').forEach(b=>b.addEventListener('click',()=>chooseClutch(b.dataset.clutch)));$('[data-loot]')?.addEventListener('click',openReward);document.querySelectorAll('[data-reward]').forEach(b=>b.addEventListener('click',()=>chooseReward(b.dataset.reward)));document.querySelectorAll('[data-reward-player]').forEach(b=>b.addEventListener('click',()=>chooseRewardPlayer(b.dataset.rewardPlayer)));$('[data-retry]')?.addEventListener('click',openBoss);$('[data-hub]')?.addEventListener('click',goHub);$('[data-training]')?.addEventListener('click',openTraining);document.querySelectorAll('[data-training-path]').forEach(b=>b.addEventListener('click',()=>chooseTrainingPath(b.dataset.trainingPath)));document.querySelectorAll('[data-training-target]').forEach(b=>b.addEventListener('click',()=>chooseTrainingTarget(b.dataset.trainingTarget)));$('[data-roster-info]')?.addEventListener('click',()=>toast(`当前阵容能力 ${Math.round(team().power)}，预算 ${Y.budgetUsed(state.roster)}/${state.budget}`))}

  state=load();if(!['home','team_select','starter_pack','hub','boss_brief','boss_mid','boss_clutch','boss_result','reward','reward_player','training','training_target'].includes(state.phase))state.phase='home';render();
})();
