(function(root){
  'use strict';
  const STYLE_LABELS={SHOOTING:'外线火力',DEFENSE:'换防铁军',STAR_ISO:'巨星单打',TWIN_TOWERS:'双塔护框',SMALL_BALL:'五外小球',FAST_BREAK:'转换冲击',BALANCED:'均衡体系'};
  const STYLE_BOOST={SHOOTING:1.15,DEFENSE:1.35,STAR_ISO:1.05,TWIN_TOWERS:1.25,SMALL_BALL:1.15,FAST_BREAK:.9,BALANCED:.8};
  const COUNTERS={SHOOTING:['DEFENSE','SMALL_BALL'],TWIN_TOWER:['SHOOTING','SMALL_BALL'],SUPERSTAR:['DEFENSE'],SMALL_BALL:['TWIN_TOWERS','DEFENSE'],TRANSITION:['BALANCED','DEFENSE'],DEFENSE:['SHOOTING'],TEAM:['STAR_ISO'],CLUTCH:['BALANCED']};
  const REPAIR_HEXES=new Set(['share_ball','superstar_ball','gods']);
  const RARITY_RANK={RARE:1,EPIC:2,LEGENDARY:3};
  const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
  function weakLink(H,state){const starters=state.starterIds.map(id=>state.roster.find(p=>p.id===id)).filter(Boolean),lowest=starters.length?Math.min(...starters.map(H.playerDef)):85;return{lowest,base:lowest>=85?0:lowest>=80?.5:lowest>=75?1:lowest>=70?2:lowest>=65?3.5:5};}
  function coreHierarchy(H,state){const cores=state.coreIds.map(id=>state.roster.find(p=>p.id===id)).filter(Boolean);if(cores.length!==3)return{score:-1,grade:'错配'};const first=cores[0],second=cores[1],third=cores[2];let score=0;score+=H.playerOff(first)>=90&&first.hidden.usage>=4?1:-.7;score+=(second.hidden.offball+second.hidden.fit)>=7?.55:-.35;score+=(third.hidden.offball+third.hidden.fit)>=7||H.playerDef(third)>=85?.55:-.35;score-=Math.min(1.2,(state.roster.indexOf(first)===-1?1:0));return{score:Math.round(score*100)/100,grade:score>=1.5?'合理':score>=.4?'可用':'错配'};}
  function usageConflict(state,team){const severity=Math.max(0,team.usage-18.5),repaired=state.hexIds.some(id=>REPAIR_HEXES.has(id));return{severity,repaired,band:team.usage>20?'严重':team.usage>18.5?'较高':team.usage>15.5?'轻微':'顺畅'};}
  function mainBuild(team){return(team.builds||[])[0]||null;}
  function seriesAdaptation(team,style,seriesGame,tactic){const build=mainBuild(team);if(!build||build.level<3||!(COUNTERS[build.tag]||[]).includes(style)||seriesGame<2)return 0;const steps=[0,0,1.1,1.5,2,2.45,2.8],raw=steps[Math.min(6,seriesGame)];return tactic==='system'?raw*.4:raw;}
  function applyTactic(team,tactic,style,seriesGame){const t={...team},notes=[];if(tactic==='inside'){t.offense+=3;t.rebound+=2;t.space-=2;t.power+=style==='SMALL_BALL'?1.25:style==='TWIN_TOWERS'?.15:.65;notes.push('终结+3 · 篮板+2 · 空间-2');}if(tactic==='short'){t.coreBoost=(t.coreBoost||1)*1.10;t.injuryRisk=(t.injuryRisk||0)+.04;t.power+=seriesGame>=5?.85:1.55;notes.push('主力权重+10% · 后程体能风险');}if(tactic==='system'){t.chemistry=clamp(t.chemistry+3,40,100);t.power+=.75;notes.push('化学反应+3 · 适应惩罚降低');}return{team:t,notes};}
  function playoffMatchup(H,V,state,{round=0,seriesGame=0,style='BALANCED',tactic=null,basePower=88}={}){let team=V.enhancedTeam(H,state,true);const tacticResult=applyTactic(team,tactic,style,seriesGame);team=tacticResult.team;const weak=weakLink(H,state),usage=usageConflict(state,team),core=coreHierarchy(H,state),teamBuild=(team.builds||[]).find(b=>b.tag==='TEAM'),clutchBuild=(team.builds||[]).find(b=>b.tag==='CLUTCH'),legendCount=team.starters.filter(p=>p.tier==='LEGEND').length;const weakPenalty=Math.min(2.5,weak.base*[.16,.28,.42,.56][round]);const usagePenalty=Math.min(3.2,usage.severity*.52*[1.15,1.2,1.25,1.3][round]*(usage.repaired?.35:1));const coreModifier=clamp(core.score*.62,-.9,1.2),buildModifier=(teamBuild?.level===3?2.3:0)+(clutchBuild?.level||0)*1.65,starCeiling=!usage.repaired&&usage.severity>=4&&legendCount>=4?2.5:0;team.power=Math.round(clamp(team.power-weakPenalty-usagePenalty+coreModifier+buildModifier+starCeiling,40,105)*10)/10;team.chemistry=Math.round(clamp(team.chemistry+(core.score>=1.5?1:core.score<0?-.5:0),40,100));const adaptation=seriesAdaptation(team,style,seriesGame,tactic),aiBoost=STYLE_BOOST[style]||1;const opponent={name:`${STYLE_LABELS[style]||'联盟强队'}`,style,power:Math.round((basePower+aiBoost+adaptation)*10)/10};return{team,opponent,details:{weakPenalty:+weakPenalty.toFixed(2),usagePenalty:+usagePenalty.toFixed(2),coreModifier:+coreModifier.toFixed(2),buildModifier:+buildModifier.toFixed(2),starCeiling:+starCeiling.toFixed(2),coreGrade:core.grade,adaptation:+adaptation.toFixed(2),aiBoost,tacticNotes:tacticResult.notes,styleLabel:STYLE_LABELS[style]||style,usageBand:usage.band,usageRepaired:usage.repaired}};}
  function sortedEndings(V,ids=[]){return[...ids].sort((a,b)=>(RARITY_RANK[V.endingById(b)?.rarity]||0)-(RARITY_RANK[V.endingById(a)?.rarity]||0));}
  function firstGameGuidedOffer(H,V,state,baseOffer){if(!state.isFirstGame||state.gameMode!=='NORMAL'||!state.firstBuildTag||(state.firstGameGuidanceUses||0)>=2)return baseOffer;const rng=V.rngFor(state.seed,'first_game_build',state.hexStep),chance=.20;if(rng()>=chance)return baseOffer;const replaced=H.hexes.find(h=>h.id===baseOffer[2]),sameQuality=H.hexes.filter(h=>h.quality===replaced?.quality),pool=sameQuality.length?sameQuality:H.hexes,candidates=pool.filter(h=>!state.hexIds.includes(h.id)&&!baseOffer.includes(h.id)&&(V.BUILD_TAGS[h.id]||[]).includes(state.firstBuildTag));if(!candidates.length)return baseOffer;const replacement=candidates[Math.floor(rng()*candidates.length)];state.firstGameGuidanceUses=(state.firstGameGuidanceUses||0)+1;return[baseOffer[0],baseOffer[1],replacement.id];}
  root.HexV021={STYLE_LABELS,STYLE_BOOST,COUNTERS,REPAIR_HEXES,RARITY_RANK,weakLink,coreHierarchy,usageConflict,mainBuild,seriesAdaptation,applyTactic,playoffMatchup,sortedEndings,firstGameGuidedOffer};
})(typeof globalThis!=='undefined'?globalThis:window);
