(function(root){
  'use strict';

  const BUILD_HEXES={
    SHOOTING:['three_rain','one_star_four_shooters','cosmic','hot_hand'],
    SMALL_BALL:['death_lineup','switch_everything','run_gun','cosmic'],
    TRANSITION:['transition','run_gun','youth','endless_energy'],
    TEAM:['share_ball','all_soldiers','five_as_one','bench_mob'],
    DEFENSE:['iron_defense','switch_everything','defense_titles','fourth_quarter'],
    PLAYMAKING:['share_ball','five_as_one','absolute_core','superstar_ball'],
    PAINT:['paint_bully','twin_towers','second_chance','defense_titles'],
    SUPERSTAR:['superstar_ball','absolute_core','fourth_quarter','gods']
  };
  const BUDGETS={CONTENDER:{label:'争冠',delta:2.2,legendCap:3},PLAYOFF:{label:'季后赛',delta:0,legendCap:2},AVERAGE:{label:'中游',delta:-2.2,legendCap:1},REBUILDING:{label:'重建',delta:-4.8,legendCap:1}};
  const TEAM_ROWS=[
    ['ATL','Atlanta Hawks','亚特兰大老鹰','EAST','Southeast',['人类电影精华','快速进攻','锋线传统'],['TRANSITION','SUPERSTAR'],['#e03a3e','#fdb927'],'1959|Bob Pettit|鲍勃·佩蒂特|PF|LEGEND|BIG;1986|Dominique Wilkins|多米尼克·威尔金斯|SF|LEGEND|SCORER;2021|Trae Young|特雷·杨|PG|ALL_NBA|PLAYMAKER;1994|Dikembe Mutombo|迪肯贝·穆托姆博|C|ALL_NBA|BIG;2015|Al Horford|艾尔·霍福德|C,PF|STAR|ALLROUND;2007|Joe Johnson|乔·约翰逊|SG,SF|STAR|SCORER;1969|Lou Hudson|卢·哈德森|SG|STAR|SHOOTER;1998|Steve Smith|史蒂夫·史密斯|SG|STAR|SHOOTER;1960|Cliff Hagan|克里夫·哈根|SF|STAR|SCORER'],
    ['BOS','Boston Celtics','波士顿凯尔特人','EAST','Atlantic',['豪门','团队篮球','冠军传统'],['TEAM','DEFENSE','SHOOTING'],['#007a33','#ba9653'],'1965|Bill Russell|比尔·拉塞尔|C|LEGEND|BIG;1986|Larry Bird|拉里·伯德|SF,PF|LEGEND|ALLROUND;1971|John Havlicek|约翰·哈夫利切克|SF,SG|LEGEND|ALLROUND;2008|Paul Pierce|保罗·皮尔斯|SF|ALL_NBA|SCORER;2024|Jayson Tatum|杰森·塔图姆|SF,PF|ALL_NBA|ALLROUND;1987|Kevin McHale|凯文·麦克海尔|PF|ALL_NBA|BIG;1984|Robert Parish|罗伯特·帕里什|C|STAR|BIG;1957|Bob Cousy|鲍勃·库西|PG|LEGEND|PLAYMAKER;2008|Kevin Garnett|凯文·加内特|PF,C|LEGEND|DEFENDER'],
    ['BKN','Brooklyn Nets','布鲁克林篮网','EAST','Atlantic',['新泽西传承','巨星实验','后场创造'],['SUPERSTAR','PLAYMAKING','SHOOTING'],['#000000','#ffffff'],'2002|Jason Kidd|贾森·基德|PG|ALL_NBA|PLAYMAKER;2021|Kevin Durant|凯文·杜兰特|SF,PF|LEGEND|SCORER;1976|Julius Erving|朱利叶斯·欧文|SF|LEGEND|ALLROUND;2005|Vince Carter|文斯·卡特|SG,SF|ALL_NBA|SCORER;2013|Brook Lopez|布鲁克·洛佩斯|C|STAR|BIG;1983|Buck Williams|巴克·威廉姆斯|PF|STAR|DEFENDER;1993|Drazen Petrovic|德拉任·彼得洛维奇|SG|STAR|SHOOTER;2021|Kyrie Irving|凯里·欧文|PG,SG|ALL_NBA|SCORER;2021|James Harden|詹姆斯·哈登|PG,SG|ALL_NBA|PLAYMAKER'],
    ['CHA','Charlotte Hornets','夏洛特黄蜂','EAST','Southeast',['蜂鸣快攻','小球市斗志','后卫传统'],['TRANSITION','PLAYMAKING'],['#1d1160','#00788c'],'2017|Kemba Walker|肯巴·沃克|PG|ALL_NBA|SCORER;1992|Larry Johnson|拉里·约翰逊|PF|ALL_NBA|ALLROUND;1995|Alonzo Mourning|阿朗佐·莫宁|C|ALL_NBA|BIG;1997|Glen Rice|格伦·莱斯|SF|ALL_NBA|SHOOTER;2010|Gerald Wallace|杰拉德·华莱士|SF|STAR|DEFENDER;2001|Baron Davis|拜伦·戴维斯|PG|STAR|PLAYMAKER;1994|Muggsy Bogues|马格西·博格斯|PG|ROLE|PLAYMAKER;1993|Dell Curry|戴尔·库里|SG|ROLE|SHOOTER;2022|LaMelo Ball|拉梅洛·鲍尔|PG|STAR|PLAYMAKER'],
    ['CHI','Chicago Bulls','芝加哥公牛','EAST','Central',['王朝','三角进攻','强硬防守'],['SUPERSTAR','DEFENSE','TRANSITION'],['#ce1141','#000000'],'1991|Michael Jordan|迈克尔·乔丹|SG,SF|LEGEND|SCORER;1996|Scottie Pippen|斯科蒂·皮蓬|SF,PG|LEGEND|ALLROUND;1996|Dennis Rodman|丹尼斯·罗德曼|PF,C|ALL_NBA|DEFENDER;2011|Derrick Rose|德里克·罗斯|PG|LEGEND|SCORER;2015|Jimmy Butler|吉米·巴特勒|SG,SF|ALL_NBA|ALLROUND;2014|Joakim Noah|乔金·诺阿|C|ALL_NBA|DEFENDER;1992|Horace Grant|霍勒斯·格兰特|PF|STAR|BIG;1996|Toni Kukoc|托尼·库科奇|SF,PF|STAR|ALLROUND;1978|Artis Gilmore|阿蒂斯·吉尔摩|C|LEGEND|BIG'],
    ['CLE','Cleveland Cavaliers','克利夫兰骑士','EAST','Central',['克城英雄','冲击篮筐','双塔'],['SUPERSTAR','PAINT','DEFENSE'],['#860038','#fdbb30'],'2016|LeBron James|勒布朗·詹姆斯|SF,PG|LEGEND|ALLROUND;1989|Mark Price|马克·普莱斯|PG|ALL_NBA|SHOOTER;1992|Brad Daugherty|布拉德·多尔蒂|C|ALL_NBA|BIG;2016|Kyrie Irving|凯里·欧文|PG|ALL_NBA|SCORER;2017|Kevin Love|凯文·乐福|PF,C|STAR|SHOOTER;1989|Larry Nance|拉里·南斯|PF|STAR|DEFENDER;2009|Zydrunas Ilgauskas|扎伊德鲁纳斯·伊尔戈斯卡斯|C|STAR|BIG;1974|Austin Carr|奥斯汀·卡尔|SG|STAR|SCORER;2023|Donovan Mitchell|多诺万·米切尔|SG,PG|ALL_NBA|SCORER'],
    ['DET','Detroit Pistons','底特律活塞','EAST','Central',['坏孩子','铁血防守','蓝领'],['DEFENSE','TEAM','PAINT'],['#c8102e','#1d42ba'],'1990|Isiah Thomas|伊塞亚·托马斯|PG|LEGEND|PLAYMAKER;1989|Joe Dumars|乔·杜马斯|SG|ALL_NBA|DEFENDER;2004|Ben Wallace|本·华莱士|C|ALL_NBA|DEFENDER;1989|Bill Laimbeer|比尔·兰比尔|C|STAR|BIG;1997|Grant Hill|格兰特·希尔|SF,PG|ALL_NBA|ALLROUND;1990|Dennis Rodman|丹尼斯·罗德曼|PF|ALL_NBA|DEFENDER;2006|Richard Hamilton|理查德·汉密尔顿|SG|STAR|SHOOTER;2006|Chauncey Billups|昌西·比卢普斯|PG|ALL_NBA|PLAYMAKER;1974|Dave Bing|戴夫·宾|PG|ALL_NBA|SCORER'],
    ['IND','Indiana Pacers','印第安纳步行者','EAST','Central',['米勒时刻','团队执行','内外均衡'],['TEAM','SHOOTING','PLAYMAKING'],['#002d62','#fdbb30'],'2000|Reggie Miller|雷吉·米勒|SG|LEGEND|SHOOTER;1971|Mel Daniels|梅尔·丹尼尔斯|C|LEGEND|BIG;1975|George McGinnis|乔治·麦金尼斯|PF|LEGEND|ALLROUND;2004|Jermaine ONeal|杰梅因·奥尼尔|PF,C|ALL_NBA|BIG;2014|Paul George|保罗·乔治|SF,SG|ALL_NBA|ALLROUND;1998|Rik Smits|里克·施密茨|C|STAR|BIG;2000|Mark Jackson|马克·杰克逊|PG|ROLE|PLAYMAKER;2018|Victor Oladipo|维克托·奥拉迪波|SG|ALL_NBA|ALLROUND;2024|Tyrese Haliburton|泰瑞斯·哈利伯顿|PG|ALL_NBA|PLAYMAKER'],
    ['MIA','Miami Heat','迈阿密热火','EAST','Southeast',['热火文化','铁血防守','巨星'],['DEFENSE','SUPERSTAR','TEAM'],['#98002e','#f9a01b'],'2009|Dwyane Wade|德维恩·韦德|SG,PG|LEGEND|SCORER;2013|LeBron James|勒布朗·詹姆斯|SF,PF|LEGEND|ALLROUND;1999|Alonzo Mourning|阿朗佐·莫宁|C|ALL_NBA|DEFENDER;2012|Chris Bosh|克里斯·波什|PF,C|ALL_NBA|ALLROUND;2020|Jimmy Butler|吉米·巴特勒|SF,SG|ALL_NBA|ALLROUND;2023|Bam Adebayo|巴姆·阿德巴约|C,PF|ALL_NBA|DEFENDER;1997|Tim Hardaway|蒂姆·哈达威|PG|ALL_NBA|PLAYMAKER;2005|Shaquille ONeal|沙奎尔·奥尼尔|C|ALL_NBA|BIG;1992|Glen Rice|格伦·莱斯|SF|STAR|SHOOTER'],
    ['MIL','Milwaukee Bucks','密尔沃基雄鹿','EAST','Central',['长人传统','攻防核心','冠军底蕴'],['PAINT','DEFENSE','SUPERSTAR'],['#00471b','#eee1c6'],'2021|Giannis Antetokounmpo|扬尼斯·阿德托昆博|PF,C|LEGEND|ALLROUND;1971|Kareem Abdul-Jabbar|卡里姆·阿卜杜尔-贾巴尔|C|LEGEND|BIG;1971|Oscar Robertson|奥斯卡·罗伯特森|PG|LEGEND|PLAYMAKER;1983|Sidney Moncrief|西德尼·蒙克利夫|SG|ALL_NBA|DEFENDER;2001|Ray Allen|雷·阿伦|SG|ALL_NBA|SHOOTER;2021|Khris Middleton|克里斯·米德尔顿|SF|STAR|SHOOTER;1979|Marques Johnson|马奎斯·约翰逊|SF|ALL_NBA|SCORER;1974|Bob Dandridge|鲍勃·丹德里奇|SF|STAR|ALLROUND;2021|Brook Lopez|布鲁克·洛佩斯|C|STAR|DEFENDER'],
    ['NYK','New York Knicks','纽约尼克斯','EAST','Atlantic',['麦迪逊广场花园','铁血内线','纽约巨星'],['DEFENSE','PAINT','SUPERSTAR'],['#006bb6','#f58426'],'1970|Walt Frazier|沃尔特·弗雷泽|PG|LEGEND|ALLROUND;1990|Patrick Ewing|帕特里克·尤因|C|LEGEND|BIG;1970|Willis Reed|威利斯·里德|C,PF|LEGEND|BIG;2013|Carmelo Anthony|卡梅罗·安东尼|SF,PF|ALL_NBA|SCORER;1985|Bernard King|伯纳德·金|SF|ALL_NBA|SCORER;1973|Earl Monroe|厄尔·门罗|SG,PG|STAR|SCORER;1993|John Starks|约翰·斯塔克斯|SG|STAR|DEFENDER;1994|Charles Oakley|查尔斯·奥克利|PF|STAR|DEFENDER;2024|Jalen Brunson|杰伦·布伦森|PG|ALL_NBA|SCORER'],
    ['ORL','Orlando Magic','奥兰多魔术','EAST','Southeast',['天赋中锋','魔术双星','年轻锋线'],['PAINT','SUPERSTAR','TRANSITION'],['#0077c0','#c4ced4'],'1995|Shaquille ONeal|沙奎尔·奥尼尔|C|LEGEND|BIG;1996|Penny Hardaway|安芬尼·哈达威|PG,SG|ALL_NBA|PLAYMAKER;2011|Dwight Howard|德怀特·霍华德|C|LEGEND|DEFENDER;2003|Tracy McGrady|特雷西·麦克格雷迪|SG,SF|LEGEND|SCORER;2003|Grant Hill|格兰特·希尔|SF|STAR|ALLROUND;1995|Nick Anderson|尼克·安德森|SG|STAR|SHOOTER;1995|Horace Grant|霍勒斯·格兰特|PF|STAR|DEFENDER;2019|Nikola Vucevic|尼古拉·武切维奇|C|STAR|BIG;2024|Franz Wagner|弗朗茨·瓦格纳|SF|STAR|ALLROUND'],
    ['PHI','Philadelphia 76ers','费城76人','EAST','Atlantic',['传奇中锋','费城精神','单打巨星'],['SUPERSTAR','PAINT','DEFENSE'],['#006bb6','#ed174c'],'1967|Wilt Chamberlain|威尔特·张伯伦|C|LEGEND|BIG;1983|Julius Erving|朱利叶斯·欧文|SF|LEGEND|ALLROUND;2001|Allen Iverson|阿伦·艾弗森|PG,SG|LEGEND|SCORER;1983|Moses Malone|摩西·马龙|C|LEGEND|BIG;1990|Charles Barkley|查尔斯·巴克利|PF,SF|LEGEND|ALLROUND;2023|Joel Embiid|乔尔·恩比德|C|LEGEND|BIG;1968|Hal Greer|哈尔·格里尔|SG|ALL_NBA|SCORER;1983|Maurice Cheeks|莫里斯·奇克斯|PG|STAR|DEFENDER;1969|Billy Cunningham|比利·坎宁安|SF|LEGEND|ALLROUND'],
    ['TOR','Toronto Raptors','多伦多猛龙','EAST','Atlantic',['北境之王','锋线群','全能防守'],['DEFENSE','TEAM','TRANSITION'],['#ce1141','#000000'],'2001|Vince Carter|文斯·卡特|SG,SF|ALL_NBA|SCORER;2019|Kawhi Leonard|科怀·伦纳德|SF,SG|LEGEND|ALLROUND;2019|Kyle Lowry|凯尔·洛瑞|PG|ALL_NBA|PLAYMAKER;2017|DeMar DeRozan|德马尔·德罗赞|SG,SF|ALL_NBA|SCORER;2010|Chris Bosh|克里斯·波什|PF,C|ALL_NBA|ALLROUND;2019|Pascal Siakam|帕斯卡尔·西亚卡姆|PF,SF|STAR|ALLROUND;2022|Fred VanVleet|弗雷德·范弗利特|PG|STAR|DEFENDER;2019|Marc Gasol|马克·加索尔|C|ALL_NBA|DEFENDER;2024|Scottie Barnes|斯科蒂·巴恩斯|SF,PF|STAR|ALLROUND'],
    ['WAS','Washington Wizards','华盛顿奇才','EAST','Southeast',['子弹传承','后场火力','全能锋线'],['PLAYMAKING','SUPERSTAR','TRANSITION'],['#002b5c','#e31837'],'1978|Wes Unseld|韦斯·昂塞尔德|C|LEGEND|BIG;1975|Elvin Hayes|埃尔文·海耶斯|PF,C|LEGEND|BIG;1971|Earl Monroe|厄尔·门罗|SG,PG|ALL_NBA|SCORER;2007|Gilbert Arenas|吉尔伯特·阿里纳斯|PG|ALL_NBA|SCORER;2017|John Wall|约翰·沃尔|PG|ALL_NBA|PLAYMAKER;2021|Bradley Beal|布拉德利·比尔|SG|ALL_NBA|SCORER;2008|Antawn Jamison|安托万·贾米森|PF,SF|STAR|SCORER;1969|Gus Johnson|格斯·约翰逊|PF|ALL_NBA|DEFENDER;2008|Caron Butler|卡隆·巴特勒|SF|STAR|ALLROUND'],
    ['DAL','Dallas Mavericks','达拉斯独行侠','WEST','Southwest',['欧洲核心','单核传奇','空间进攻'],['SHOOTING','PLAYMAKING','SUPERSTAR'],['#00538c','#b8c4ca'],'2011|Dirk Nowitzki|德克·诺维茨基|PF,C|LEGEND|SHOOTER;2024|Luka Doncic|卢卡·东契奇|PG,SF|LEGEND|PLAYMAKER;1996|Jason Kidd|贾森·基德|PG|ALL_NBA|PLAYMAKER;2003|Steve Nash|史蒂夫·纳什|PG|ALL_NBA|SHOOTER;1984|Mark Aguirre|马克·阿奎尔|SF|ALL_NBA|SCORER;2000|Michael Finley|迈克尔·芬利|SG,SF|STAR|ALLROUND;2011|Jason Terry|杰森·特里|SG,PG|STAR|SHOOTER;1984|Rolando Blackman|罗兰多·布莱克曼|SG|STAR|SCORER;2011|Tyson Chandler|泰森·钱德勒|C|ALL_NBA|DEFENDER'],
    ['DEN','Denver Nuggets','丹佛掘金','WEST','Northwest',['高原主场','传球中锋','进攻万花筒'],['PLAYMAKING','TEAM','PAINT'],['#0e2240','#fec524'],'2023|Nikola Jokic|尼古拉·约基奇|C,PG|LEGEND|PLAYMAKER;1983|Alex English|亚历克斯·英格利什|SF|LEGEND|SCORER;1977|David Thompson|大卫·汤普森|SG,SF|LEGEND|SCORER;2009|Carmelo Anthony|卡梅罗·安东尼|SF|ALL_NBA|SCORER;1994|Dikembe Mutombo|迪肯贝·穆托姆博|C|ALL_NBA|DEFENDER;1988|Fat Lever|法特·利弗|PG|ALL_NBA|ALLROUND;2009|Chauncey Billups|昌西·比卢普斯|PG|ALL_NBA|PLAYMAKER;1977|Dan Issel|丹·伊塞尔|C,PF|LEGEND|BIG;2023|Jamal Murray|贾马尔·穆雷|PG|STAR|SCORER'],
    ['GSW','Golden State Warriors','金州勇士','WEST','Pacific',['三分革命','小球','快速传导'],['SHOOTING','SMALL_BALL','TEAM'],['#1d428a','#ffc72c'],'2016|Stephen Curry|斯蒂芬·库里|PG|LEGEND|SHOOTER;1962|Wilt Chamberlain|威尔特·张伯伦|C|LEGEND|BIG;1975|Rick Barry|里克·巴里|SF|LEGEND|ALLROUND;2017|Kevin Durant|凯文·杜兰特|SF,PF|LEGEND|SCORER;2016|Klay Thompson|克莱·汤普森|SG,SF|ALL_NBA|SHOOTER;2016|Draymond Green|德雷蒙德·格林|PF,C|ALL_NBA|DEFENDER;1992|Chris Mullin|克里斯·穆林|SF|ALL_NBA|SHOOTER;1968|Nate Thurmond|内特·瑟蒙德|C|LEGEND|DEFENDER;1991|Tim Hardaway|蒂姆·哈达威|PG|ALL_NBA|PLAYMAKER'],
    ['HOU','Houston Rockets','休斯顿火箭','WEST','Southwest',['梦幻脚步','中锋传统','单打火力'],['PAINT','SUPERSTAR','SHOOTING'],['#ce1141','#000000'],'1994|Hakeem Olajuwon|哈基姆·奥拉朱旺|C|LEGEND|BIG;2018|James Harden|詹姆斯·哈登|PG,SG|LEGEND|PLAYMAKER;1982|Moses Malone|摩西·马龙|C|LEGEND|BIG;2007|Yao Ming|姚明|C|ALL_NBA|BIG;2005|Tracy McGrady|特雷西·麦克格雷迪|SG,SF|ALL_NBA|SCORER;1997|Clyde Drexler|克莱德·德雷克斯勒|SG,SF|ALL_NBA|ALLROUND;1979|Calvin Murphy|卡尔文·墨菲|PG|STAR|SCORER;1979|Rudy Tomjanovich|鲁迪·汤姆贾诺维奇|SF,PF|STAR|ALLROUND;1986|Ralph Sampson|拉尔夫·桑普森|C,PF|ALL_NBA|BIG'],
    ['LAC','Los Angeles Clippers','洛杉矶快船','WEST','Pacific',['空接之城','锋线群','洛城挑战者'],['TRANSITION','DEFENSE','SUPERSTAR'],['#c8102e','#1d428a'],'1975|Bob McAdoo|鲍勃·麦卡杜|C,PF|LEGEND|SCORER;2014|Chris Paul|克里斯·保罗|PG|LEGEND|PLAYMAKER;2014|Blake Griffin|布雷克·格里芬|PF|ALL_NBA|ALLROUND;2021|Kawhi Leonard|科怀·伦纳德|SF|ALL_NBA|ALLROUND;2021|Paul George|保罗·乔治|SF,SG|ALL_NBA|ALLROUND;2006|Elton Brand|埃尔顿·布兰德|PF,C|ALL_NBA|BIG;2016|DeAndre Jordan|德安德烈·乔丹|C|ALL_NBA|DEFENDER;1985|Norm Nixon|诺姆·尼克松|PG|STAR|PLAYMAKER;2018|Lou Williams|路易斯·威廉姆斯|SG,PG|STAR|SCORER'],
    ['LAL','Los Angeles Lakers','洛杉矶湖人','WEST','Pacific',['豪门','Showtime','超级中锋传统'],['SUPERSTAR','PAINT','TRANSITION'],['#552583','#fdb927'],'1987|Magic Johnson|魔术师·约翰逊|PG,SF|LEGEND|PLAYMAKER;2006|Kobe Bryant|科比·布莱恩特|SG,SF|LEGEND|SCORER;1972|Jerry West|杰里·韦斯特|PG,SG|LEGEND|ALLROUND;2020|LeBron James|勒布朗·詹姆斯|SF,PG|LEGEND|ALLROUND;2000|Shaquille ONeal|沙奎尔·奥尼尔|C|LEGEND|BIG;1980|Kareem Abdul-Jabbar|卡里姆·阿卜杜尔-贾巴尔|C|LEGEND|BIG;2020|Anthony Davis|安东尼·戴维斯|PF,C|ALL_NBA|DEFENDER;1988|James Worthy|詹姆斯·沃西|SF|ALL_NBA|SCORER;1963|Elgin Baylor|埃尔金·贝勒|SF|LEGEND|ALLROUND'],
    ['MEM','Memphis Grizzlies','孟菲斯灰熊','WEST','Southwest',['磨砺之城','黑白双熊','强硬防守'],['DEFENSE','PAINT','TEAM'],['#5d76a9','#12173f'],'2013|Marc Gasol|马克·加索尔|C|ALL_NBA|DEFENDER;2017|Mike Conley|迈克·康利|PG|STAR|PLAYMAKER;2011|Zach Randolph|扎克·兰多夫|PF|ALL_NBA|BIG;2022|Ja Morant|贾·莫兰特|PG|ALL_NBA|SCORER;2006|Pau Gasol|保罗·加索尔|PF,C|ALL_NBA|ALLROUND;2013|Tony Allen|托尼·阿伦|SG|STAR|DEFENDER;2005|Shane Battier|肖恩·巴蒂尔|SF|STAR|DEFENDER;1999|Shareef Abdur-Rahim|谢里夫·阿卜杜-拉希姆|PF,SF|STAR|SCORER;2023|Desmond Bane|德斯蒙德·贝恩|SG|STAR|SHOOTER'],
    ['MIN','Minnesota Timberwolves','明尼苏达森林狼','WEST','Northwest',['狼王','双塔','年轻天赋'],['PAINT','DEFENSE','TRANSITION'],['#0c2340','#78be20'],'2004|Kevin Garnett|凯文·加内特|PF,C|LEGEND|ALLROUND;2022|Karl-Anthony Towns|卡尔-安东尼·唐斯|C,PF|ALL_NBA|SHOOTER;2024|Anthony Edwards|安东尼·爱德华兹|SG,SF|ALL_NBA|SCORER;2014|Kevin Love|凯文·乐福|PF,C|ALL_NBA|ALLROUND;2004|Sam Cassell|萨姆·卡塞尔|PG|STAR|PLAYMAKER;2004|Latrell Sprewell|拉特里尔·斯普雷维尔|SG,SF|STAR|SCORER;2017|Ricky Rubio|里基·卢比奥|PG|STAR|PLAYMAKER;2024|Rudy Gobert|鲁迪·戈贝尔|C|ALL_NBA|DEFENDER;2002|Wally Szczerbiak|沃利·斯泽比亚克|SF|STAR|SHOOTER'],
    ['NOP','New Orleans Pelicans','新奥尔良鹈鹕','WEST','Southwest',['新奥尔良后场','长臂锋线','禁区天赋'],['TRANSITION','PAINT','PLAYMAKING'],['#0c2340','#85714d'],'2008|Chris Paul|克里斯·保罗|PG|LEGEND|PLAYMAKER;2018|Anthony Davis|安东尼·戴维斯|PF,C|LEGEND|DEFENDER;2021|Zion Williamson|锡安·威廉森|PF|ALL_NBA|SCORER;2018|Jrue Holiday|朱·霍勒迪|PG,SG|ALL_NBA|DEFENDER;2020|Brandon Ingram|布兰登·英格拉姆|SF|ALL_NBA|SCORER;2009|David West|大卫·韦斯特|PF|STAR|BIG;2004|Baron Davis|拜伦·戴维斯|PG|ALL_NBA|PLAYMAKER;2008|Peja Stojakovic|佩贾·斯托贾科维奇|SF|STAR|SHOOTER;2018|DeMarcus Cousins|德马库斯·考辛斯|C|ALL_NBA|BIG'],
    ['OKC','Oklahoma City Thunder','俄克拉荷马城雷霆','WEST','Northwest',['雷霆三少','运动天赋','西雅图传承'],['TRANSITION','SUPERSTAR','DEFENSE'],['#007ac1','#ef3b24'],'2014|Kevin Durant|凯文·杜兰特|SF,PF|LEGEND|SCORER;2017|Russell Westbrook|拉塞尔·威斯布鲁克|PG|LEGEND|SCORER;2012|James Harden|詹姆斯·哈登|SG,PG|ALL_NBA|PLAYMAKER;2024|Shai Gilgeous-Alexander|谢伊·吉尔杰斯-亚历山大|PG,SG|LEGEND|SCORER;2005|Ray Allen|雷·阿伦|SG|ALL_NBA|SHOOTER;2000|Gary Payton|加里·佩顿|PG|LEGEND|DEFENDER;1996|Shawn Kemp|肖恩·坎普|PF|ALL_NBA|BIG;2012|Serge Ibaka|塞尔吉·伊巴卡|PF,C|STAR|DEFENDER;1982|Jack Sikma|杰克·西克马|C|ALL_NBA|ALLROUND'],
    ['PHX','Phoenix Suns','菲尼克斯太阳','WEST','Pacific',['七秒进攻','跑轰','中距离大师'],['TRANSITION','SHOOTING','PLAYMAKING'],['#1d1160','#e56020'],'2007|Steve Nash|史蒂夫·纳什|PG|LEGEND|PLAYMAKER;1993|Charles Barkley|查尔斯·巴克利|PF|LEGEND|ALLROUND;2024|Devin Booker|德文·布克|SG,PG|ALL_NBA|SCORER;2024|Kevin Durant|凯文·杜兰特|SF,PF|LEGEND|SCORER;2007|Amare Stoudemire|阿马雷·斯塔德迈尔|PF,C|ALL_NBA|BIG;2007|Shawn Marion|肖恩·马里昂|SF,PF|ALL_NBA|DEFENDER;2021|Chris Paul|克里斯·保罗|PG|ALL_NBA|PLAYMAKER;1990|Kevin Johnson|凯文·约翰逊|PG|ALL_NBA|SCORER;1978|Walter Davis|沃尔特·戴维斯|SG,SF|ALL_NBA|SCORER'],
    ['POR','Portland Trail Blazers','波特兰开拓者','WEST','Northwest',['撕裂之城','传奇中锋','关键后卫'],['SHOOTING','PAINT','SUPERSTAR'],['#e03a3e','#000000'],'1977|Bill Walton|比尔·沃顿|C|LEGEND|ALLROUND;1992|Clyde Drexler|克莱德·德雷克斯勒|SG,SF|LEGEND|ALLROUND;2020|Damian Lillard|达米安·利拉德|PG|LEGEND|SCORER;2015|LaMarcus Aldridge|拉马库斯·阿尔德里奇|PF,C|ALL_NBA|BIG;2009|Brandon Roy|布兰登·罗伊|SG|ALL_NBA|SCORER;2000|Rasheed Wallace|拉希德·华莱士|PF,C|STAR|DEFENDER;1999|Arvydas Sabonis|阿维达斯·萨博尼斯|C|STAR|PLAYMAKER;1991|Terry Porter|特里·波特|PG|ALL_NBA|PLAYMAKER;1977|Maurice Lucas|莫里斯·卢卡斯|PF|STAR|DEFENDER'],
    ['SAC','Sacramento Kings','萨克拉门托国王','WEST','Pacific',['普林斯顿进攻','国王复兴','传球大个'],['TEAM','PLAYMAKING','TRANSITION'],['#5a2d81','#63727a'],'1964|Oscar Robertson|奥斯卡·罗伯特森|PG|LEGEND|PLAYMAKER;1965|Jerry Lucas|杰里·卢卡斯|PF,C|LEGEND|ALLROUND;2001|Chris Webber|克里斯·韦伯|PF,C|LEGEND|PLAYMAKER;2017|DeMarcus Cousins|德马库斯·考辛斯|C|ALL_NBA|BIG;2004|Peja Stojakovic|佩贾·斯托贾科维奇|SF|ALL_NBA|SHOOTER;2004|Mike Bibby|迈克·毕比|PG|STAR|PLAYMAKER;1997|Mitch Richmond|米奇·里奇蒙德|SG|ALL_NBA|SCORER;2023|DeAaron Fox|达龙·福克斯|PG|ALL_NBA|SCORER;1973|Nate Archibald|内特·阿奇博尔德|PG|LEGEND|SCORER'],
    ['SAS','San Antonio Spurs','圣安东尼奥马刺','WEST','Southwest',['团队篮球','纪律','国际球员'],['TEAM','DEFENSE','PLAYMAKING'],['#c4ced4','#000000'],'2003|Tim Duncan|蒂姆·邓肯|PF,C|LEGEND|BIG;1995|David Robinson|大卫·罗宾逊|C|LEGEND|DEFENDER;2013|Tony Parker|托尼·帕克|PG|ALL_NBA|PLAYMAKER;2005|Manu Ginobili|马努·吉诺比利|SG,PG|ALL_NBA|ALLROUND;2017|Kawhi Leonard|科怀·伦纳德|SF,SG|LEGEND|DEFENDER;1978|George Gervin|乔治·格文|SG,SF|LEGEND|SCORER;2018|LaMarcus Aldridge|拉马库斯·阿尔德里奇|PF,C|ALL_NBA|BIG;2007|Bruce Bowen|布鲁斯·鲍文|SF|ROLE|DEFENDER;1996|Sean Elliott|肖恩·埃利奥特|SF|STAR|SHOOTER'],
    ['UTA','Utah Jazz','犹他爵士','WEST','Northwest',['挡拆传统','铁血内线','盐湖城主场'],['TEAM','PAINT','DEFENSE'],['#002b5c','#f9a01b'],'1997|Karl Malone|卡尔·马龙|PF|LEGEND|BIG;1995|John Stockton|约翰·斯托克顿|PG|LEGEND|PLAYMAKER;2021|Donovan Mitchell|多诺万·米切尔|SG,PG|ALL_NBA|SCORER;2021|Rudy Gobert|鲁迪·戈贝尔|C|ALL_NBA|DEFENDER;1977|Pete Maravich|皮特·马拉维奇|SG,PG|LEGEND|SCORER;1984|Adrian Dantley|阿德里安·丹特利|SF|ALL_NBA|SCORER;2008|Deron Williams|德隆·威廉姆斯|PG|ALL_NBA|PLAYMAKER;2004|Andrei Kirilenko|安德烈·基里连科|SF,PF|ALL_NBA|DEFENDER;2007|Carlos Boozer|卡洛斯·布泽尔|PF|STAR|BIG']
  ];

  const ARCH={
    PLAYMAKER:{fin:82,mid:84,three:82,pass:96,pd:84,id:62,reb:68,ath:86,usage:4,offball:4,fit:5,clutch:4,size:2,tags:['playmaker','creator']},
    SHOOTER:{fin:78,mid:90,three:96,pass:78,pd:82,id:58,reb:62,ath:82,usage:3,offball:5,fit:5,clutch:4,size:3,tags:['shooting','offball']},
    SCORER:{fin:94,mid:93,three:86,pass:82,pd:82,id:65,reb:70,ath:94,usage:5,offball:3,fit:4,clutch:5,size:3,tags:['creator','clutch']},
    ALLROUND:{fin:91,mid:87,three:82,pass:89,pd:92,id:84,reb:84,ath:92,usage:4,offball:4,fit:5,clutch:5,size:4,tags:['multi','playmaker','defense']},
    DEFENDER:{fin:76,mid:70,three:72,pass:76,pd:97,id:94,reb:89,ath:89,usage:2,offball:5,fit:5,clutch:4,size:4,tags:['defense','offball','rim']},
    BIG:{fin:95,mid:78,three:48,pass:75,pd:72,id:97,reb:97,ath:91,usage:4,offball:4,fit:5,clutch:4,size:5,tags:['post','rim','rebound']}
  };
  const TIER_DELTA={LEGEND:3,ALL_NBA:0,STAR:-4,ROLE:-9};
  const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
  const slug=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_|_$/g,'');
  function hash(text){let h=2166136261;for(const ch of String(text)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
  function makePlayer(teamId,row,index){const [season,enName,name,pos,tier,kind]=row.split('|'),base=ARCH[kind],j=(hash(`${teamId}|${enName}|${season}`)%7)-3,d=TIER_DELTA[tier]||0,boost=k=>clamp(base[k]+d+(k==='three'?j:Math.round(j/2)),35,99);return{id:`hist_${teamId.toLowerCase()}_${slug(enName)}_${season}`,name,enName,season,age:24+(hash(enName)%10),positions:pos.split(','),tier,teams:[teamId],primaryHistoricalTeam:teamId,seasonAge:24+(hash(enName+season)%10),archetypes:[kind,...base.tags],attributes:{fin:boost('fin'),mid:boost('mid'),three:boost('three'),pass:boost('pass'),perimeterDefense:boost('pd'),interiorDefense:boost('id'),rebound:boost('reb'),athleticism:boost('ath')},hidden:{usage:base.usage,offball:base.offball,fit:base.fit,clutch:base.clutch,consistency:tier==='LEGEND'?5:4,size:base.size},tags:[...base.tags],poolOrder:index};}
  const teams=TEAM_ROWS.map(row=>{const[id,name,chineseName,conference,division,historicalTags,preferredBuilds,colors,pool]=row;const historicalPlayers=pool.split(';').map((x,i)=>makePlayer(id,x,i));return{id,name,chineseName,abbreviation:id,conference,division,historicalTags,preferredBuilds,colors,playerPoolIds:historicalPlayers.map(p=>p.id),historicalPlayers};});
  const historicalPlayers=teams.flatMap(t=>t.historicalPlayers);
  const teamById=id=>teams.find(t=>t.id===id);
  const playerById=id=>historicalPlayers.find(p=>p.id===id);
  function seededShuffle(rows,rng){const out=[...rows];for(let i=out.length-1;i>0;i--){const j=Math.floor(rng()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
  function validateHistory(){const errors=[];for(const team of teams){for(const id of team.playerPoolIds){const p=playerById(id);if(!p)errors.push(`${team.id}: missing ${id}`);else if(!p.teams.includes(team.id))errors.push(`${p.name} -> ${team.id}`)}}return{teams:teams.length,players:historicalPlayers.length,assignments:teams.reduce((n,t)=>n+t.playerPoolIds.length,0),errors};}
  function budgetMap(seed,playerTeamId,V){const ids=seededShuffle(teams.filter(t=>t.id!==playerTeamId).map(t=>t.id),V.rngFor(seed,'v022_budget',0)),result={};ids.forEach((id,i)=>result[id]=i<6?'CONTENDER':i<15?'PLAYOFF':i<24?'AVERAGE':'REBUILDING');return result;}
  function buildAITeam(team,budget,seed,H,V){const rule=BUDGETS[budget],rng=V.rngFor(seed,`v022_roster_${team.id}`,0),shuffled=seededShuffle(team.historicalPlayers,rng),rank={LEGEND:4,ALL_NBA:3,STAR:2,ROLE:1};let legends=0;const roster=[];for(const p of shuffled.sort((a,b)=>rank[b.tier]-rank[a.tier]+(rng()-.5)*1.8)){if(p.tier==='LEGEND'&&legends>=rule.legendCap)continue;roster.push(p);if(p.tier==='LEGEND')legends++;if(roster.length===8)break}for(const p of shuffled)if(roster.length<8&&!roster.includes(p))roster.push(p);const score=p=>H.playerOff(p)*.48+H.playerDef(p)*.28+H.playerCreate(p)*.14+H.playerSpace(p)*.10,ordered=[...roster].sort((a,b)=>score(b)-score(a)),starters=ordered.slice(0,5),cores=starters.slice(0,3),weighted=[...new Set(team.preferredBuilds.flatMap(tag=>BUILD_HEXES[tag]||[]))],hexPool=[...weighted,...H.hexes.map(h=>h.id)],hexIds=[];for(const id of seededShuffle(hexPool,V.rngFor(seed,`v022_hex_${team.id}`,0)))if(!hexIds.includes(id)&&H.hexes.some(h=>h.id===id)){hexIds.push(id);if(hexIds.length===4)break}let ratings=V.enhancedTeam(H,{roster,starterIds:starters.map(p=>p.id),coreIds:cores.map(p=>p.id),hexIds},false);ratings={...ratings,power:Math.round(clamp(ratings.power+rule.delta,67,101)*10)/10};const builds=V.calculateBuilds(ratings,roster,starters.map(p=>p.id),cores.map(p=>p.id),hexIds);ratings.builds=builds;return{id:team.id,name:team.name,chineseName:team.chineseName,abbreviation:team.abbreviation,conference:team.conference,division:team.division,historicalTags:team.historicalTags,preferredBuilds:team.preferredBuilds,colors:team.colors,budget,budgetLabel:rule.label,roster,starterIds:starters.map(p=>p.id),coreIds:cores.map(p=>p.id),hexIds,ratings,wins:0,losses:0,last10:'0-0',streak:0,rank:0,leagueRank:0,playerStats:{}};}
  function createLeague(seed,playerTeamId,H,V){const budgets=budgetMap(seed,playerTeamId,V);return teams.filter(t=>t.id!==playerTeamId).map(t=>buildAITeam(t,budgets[t.id],seed,H,V));}
  function createSchedule(seed,playerTeamId,V){const own=teamById(playerTeamId),same=teams.filter(t=>t.id!==playerTeamId&&t.conference===own.conference),other=teams.filter(t=>t.conference!==own.conference),rng=V.rngFor(seed,'v022_schedule',0),schedule=[];while(schedule.length<82){const pool=schedule.length%5===4?other:same;const candidates=pool.filter(t=>schedule.slice(-2).every(id=>id!==t.id));schedule.push(candidates[Math.floor(rng()*candidates.length)].id)}return schedule;}
  function playerStatLine(p,team,games,H,V,seed){const rng=V.rngFor(seed,`v022_stats_${team.id}_${p.id}`,games),role=Math.max(0,team.coreIds.indexOf(p.id)),starter=team.starterIds.includes(p.id),usage=team.coreIds.includes(p.id)?[1.25,1.05,.9][role]:(starter?.68:.42),off=H.playerOff(p);return{gp:games,pts:+clamp((off-55)*.55*usage+(rng()-.5)*2,4,34).toFixed(1),reb:+clamp((p.attributes.rebound-42)*.12*(starter?1:.65),1,14).toFixed(1),ast:+clamp((p.attributes.pass-45)*.11*usage,1,13).toFixed(1),stl:+clamp((p.attributes.perimeterDefense-55)*.025+.5,.3,2.6).toFixed(1),blk:+clamp((p.attributes.interiorDefense-50)*.035+.25,.2,3.4).toFixed(1),fg:+clamp(.41+(off-72)*.0024,.40,.62).toFixed(3),three:+clamp(.29+(p.attributes.three-62)*.0027,.22,.49).toFixed(3)};}
  function updateLeague(state,games,H,V){const playerTeam=teamById(state.selectedTeam),playerEntry={id:playerTeam.id,name:playerTeam.name,chineseName:playerTeam.chineseName,abbreviation:playerTeam.abbreviation,conference:playerTeam.conference,division:playerTeam.division,colors:playerTeam.colors,isPlayer:true,wins:state.season.wins,losses:state.season.losses,last10:state.season.last10||'0-0',streak:state.season.streak,ratings:V.enhancedTeam(H,state,false),roster:state.roster,starterIds:state.starterIds,coreIds:state.coreIds,hexIds:state.hexIds,playerStats:{}};for(const team of state.leagueTeams){const rng=V.rngFor(state.seed,`v022_record_${team.id}`,games),pct=clamp(.5+(team.ratings.power-86)*.018+(rng()-.5)*.08,.18,.82);team.wins=Math.round(games*pct);team.losses=games-team.wins;const recent=games?Math.round(clamp(pct*Math.min(10,games)+(rng()-.5)*3,0,Math.min(10,games))):0;team.last10=`${recent}-${Math.min(10,games)-recent}`;team.streak=games?Math.round((rng()-.5)*Math.min(8,games)):0;team.playerStats=Object.fromEntries(team.roster.map(p=>[p.id,playerStatLine(p,team,games,H,V,state.seed)]));}state.leagueSnapshot=[...state.leagueTeams,playerEntry];for(const conf of ['EAST','WEST'])state.leagueSnapshot.filter(t=>t.conference===conf).sort((a,b)=>b.wins-a.wins||(b.ratings?.power||0)-(a.ratings?.power||0)).forEach((t,i)=>t.rank=i+1);[...state.leagueSnapshot].sort((a,b)=>b.wins-a.wins).forEach((t,i)=>t.leagueRank=i+1);return state.leagueSnapshot;}
  function getLeagueTeam(state,id){if(id===state.selectedTeam){const base=teamById(id);return(state.leagueSnapshot||[]).find(t=>t.id===id)||{...base,isPlayer:true,roster:state.roster,starterIds:state.starterIds,coreIds:state.coreIds,hexIds:state.hexIds,ratings:null,wins:state.season?.wins||0,losses:state.season?.losses||0}}return state.leagueTeams.find(t=>t.id===id)}
  function nextOpponent(state){return getLeagueTeam(state,state.schedule?.[state.season?.games||0])}
  function mainBuild(team){return team?.ratings?.builds?.[0]||null}
  function analyze(team){const r=team.ratings,strengths=[],weaknesses=[];if(r.offense>=90)strengths.push('顶级持球创造与终结');if(r.defense>=90)strengths.push('整体防守压迫感强');if(r.space>=90)strengths.push('外线空间足以拉开禁区');if(r.rebound>=90)strengths.push('篮板与二次进攻占优');if(r.playmaking>=90)strengths.push('传导稳定，很难被夹击切断');if(r.chemistry>=92)strengths.push('角色清晰，化学反应优秀');if(r.usage>19)weaknesses.push('多名核心需要球权');if(r.space<78)weaknesses.push('外线空间并非顶级');if(r.rebound<78)weaknesses.push('篮板保护存在缺口');if(r.defense<80)weaknesses.push('防守端存在可点名位置');if(r.playmaking<80)weaknesses.push('第二组织点不足');if(!weaknesses.length)weaknesses.push('纸面短板不明显，需要针对轮换');return{strengths:strengths.slice(0,3),weaknesses:weaknesses.slice(0,3)};}
  function tacticAdvice(playerRatings,opponent){const o=opponent.ratings,rows=[];rows.push({id:'inside',stars:o.rimProtection<88?4:2,text:o.rimProtection<88?'对手护框一般，可以持续冲击禁区。':'对手护框强，强攻内线会增加回合难度。'});rows.push({id:'short',stars:playerRatings.power>o.power?4:3,text:playerRatings.power>o.power?'核心质量占优，缩短轮换能放大优势。':'核心未明显占优，缩短轮换伴随体能风险。'});rows.push({id:'system',stars:(playerRatings.builds||[]).some(b=>b.level===3)?5:3,text:(playerRatings.builds||[]).some(b=>b.level===3)?'你的Build已经成型，坚持体系更稳。':'体系仍有提升空间，但能保持化学反应。'});return rows;}
  function leaders(state,H){const all=[];for(const team of state.leagueTeams||[])for(const p of team.roster||[]){const s=team.playerStats?.[p.id];if(s)all.push({player:p,team,value:s})}for(const p of state.roster||[]){const raw=state.season?.stats?.[p.id],gp=raw?.gp||0;if(gp)all.push({player:p,team:{abbreviation:state.selectedTeam},value:{pts:raw.pts/gp,reb:raw.reb/gp,ast:raw.ast/gp,stl:raw.stl/gp,blk:raw.blk/gp,fg:raw.fg/gp,three:raw.three/gp}})}const top=key=>[...all].sort((a,b)=>b.value[key]-a.value[key]).slice(0,5);return{scoring:top('pts'),rebounding:top('reb'),assists:top('ast'),steals:top('stl'),blocks:top('blk'),mvp:[...all].sort((a,b)=>(b.value.pts+b.value.reb*.65+b.value.ast*.8+(b.team.wins||0)*.08)-(a.value.pts+a.value.reb*.65+a.value.ast*.8+(a.team.wins||0)*.08)).slice(0,5),dpoy:[...all].sort((a,b)=>(b.value.stl*2+b.value.blk*2+b.value.reb*.35+(b.team.ratings?.defense||80)*.06)-(a.value.stl*2+a.value.blk*2+a.value.reb*.35+(a.team.ratings?.defense||80)*.06)).slice(0,5)};}
  function gameReasons(playerTeam,opponent,result){const rows=[];const sign=result.win?'✓':'✗',a=playerTeam,b=opponent.ratings;if(Math.abs(a.rebound-b.rebound)>=5)rows.push(`${sign} ${a.rebound>b.rebound?'篮板与二次进攻占优':'篮板保护落后'}`);if(Math.abs(a.space-b.space)>=5)rows.push(`${sign} ${a.space>b.space?'空间拉开了对手防线':'外线空间受到压缩'}`);if(Math.abs(a.defense-b.offense)>=5)rows.push(`${sign} ${a.defense>b.offense?'防守限制了对手核心':'对手核心创造难以限制'}`);if(a.usage>19)rows.push(`${result.win?'✓':'✗'} 高球权阵容${result.win?'仍靠关键球过关':'在末节出现冲突'}`);rows.push(`${sign} ${result.win?'关键回合执行更稳定':'对手在关键回合完成得更好'}`);return rows.slice(0,3);}
  root.HexV022={VERSION:'0.2.2',BUILD_HEXES,BUDGETS,teams,historicalPlayers,teamById,playerById,validateHistory,createLeague,createSchedule,updateLeague,getLeagueTeam,nextOpponent,mainBuild,analyze,tacticAdvice,leaders,gameReasons};
})(typeof globalThis!=='undefined'?globalThis:window);
